name: bilgi_rotasi
description: Aynı telefonda 2-6 kişilik Türkçe bilgi yarışması.
publish_to: "none"
version: 1.68.19+109
environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter_native_splash: ^2.4.8
  shared_preferences: ^2.5.5
  audioplayers: ^6.8.1
  share_plus: 10.1.2
  url_launcher: ^6.3.2
  firebase_core: ^4.12.1
  firebase_analytics: ^12.4.5
  firebase_messaging: ^16.4.3
  firebase_auth: ^6.5.6
  cloud_firestore: ^6.7.1
  cloud_functions: ^6.3.5
  firebase_app_check: ^0.4.5+2
  google_sign_in: ^7.2.0
  google_mobile_ads: 9.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  crypto: ^3.0.6
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/branding/
    - assets/sounds/
    - assets/pawns/
    - assets/questions.json
    - assets/word_hunt/
    - assets/word_hunt/gokyuzu_adalari/
    - assets/word_hunt/baslangic_limani/
    - assets/word_hunt/v5_reference_assets/


flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/branding/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#01041E"
  adaptive_icon_foreground: "assets/branding/app_icon.png"
  adaptive_icon_foreground_inset: 18

flutter_native_splash:
  color: "#24122F"
  image: assets/branding/splash_logo.png
  android: true
  ios: false
  web: false
  android_12:
    color: "#24122F"
    image: assets/branding/splash_logo.png
