import 'word_hunt_models.dart';

/// Deterministic Content Factory stokundan alınan ve production'da
/// statik olarak tutulan Orman Yolu içeriği.
///
/// Production katalog açılma kuralı burada tanımlanmaz;
/// `unlockStarsRequired` stok metadata değeridir.
class WordHuntOrmanContent {
  WordHuntOrmanContent._();

  static const List<WordHuntInfoCard> infoCards = <WordHuntInfoCard>[
    WordHuntInfoCard(
      id: 'orman-info-agac',
      word: 'AĞAÇ',
      title: 'Ağaç',
      shortFact: 'Ağaçların kökleri su ve mineralleri alırken gövdeleri yaprakları ışığa doğru taşır.',
      category: 'Doğa',
    ),
    WordHuntInfoCard(
      id: 'orman-info-mese',
      word: 'MEŞE',
      title: 'Meşe',
      shortFact: 'Meşe ağaçlarının meyvesine palamut denir; palamutlar birçok orman canlısı için besin olabilir.',
      category: 'Doğa',
    ),
    WordHuntInfoCard(
      id: 'orman-info-mantar',
      word: 'MANTAR',
      title: 'Mantar',
      shortFact: 'Mantarlar bitki değildir; birçok mantar, ormandaki organik maddelerin parçalanmasına katkı sağlar.',
      category: 'Doğa',
    ),
    WordHuntInfoCard(
      id: 'orman-info-kozalak',
      word: 'KOZALAK',
      title: 'Kozalak',
      shortFact: 'Çam gibi bazı iğne yapraklı ağaçların tohumları kozalakların pulları arasında gelişir.',
      category: 'Doğa',
    ),
    WordHuntInfoCard(
      id: 'orman-info-sincap',
      word: 'SİNCAP',
      title: 'Sincap',
      shortFact: 'Sincaplar bazı tohum ve yemişleri saklar; unutulanların bir kısmı yeni bitkilere dönüşebilir.',
      category: 'Doğa',
    ),
    WordHuntInfoCard(
      id: 'orman-info-geyik',
      word: 'GEYİK',
      title: 'Geyik',
      shortFact: 'Geyikler ot, yaprak ve sürgünlerle beslenen otçul memelilerdir.',
      category: 'Doğa',
    ),
  ];

  static const WordHuntRouteDefinition ormanYolu = WordHuntRouteDefinition(
    id: 'orman-yolu',
    title: 'Orman Yolu',
    theme: 'orman',
    unlockStarsRequired: 0,
    routeRewardId: 'reward-orman-yolu',
    levels: <WordHuntLevelDefinition>[
      WordHuntLevelDefinition(
        id: 'orman-yolu-01',
        routeId: 'orman-yolu',
        index: 1,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'ŞDKÇLŞVU',
          'UÖAASYIÜ',
          'KŞDĞREİU',
          'EBİASPĞR',
          'AİHORMAN',
          'ÖUMNHLVY',
          'ŞEİGGDHÇ',
          'IZVBLYİÇ',
        ],
        targetWords: <String>['AĞAÇ', 'YAPRAK', 'DAL', 'KÖK', 'ORMAN'],
        infoCardIds: <String>['orman-info-agac'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'orman-yolu-02',
        routeId: 'orman-yolu',
        index: 2,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'HÇEUHJÖO',
          'İŞGKÖKNM',
          'EÖUTVÜJL',
          'İŞŞOÜUİN',
          'JKERSARB',
          'VNDMİİYU',
          'NVAAZZRN',
          'UÇKNİÖUS',
        ],
        targetWords: <String>['KÖK', 'ORMAN', 'ÇAM', 'MEŞE', 'KUŞ'],
        infoCardIds: <String>['orman-info-mese'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'orman-yolu-03',
        routeId: 'orman-yolu',
        index: 3,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'COSTKİÜS',
          'ÜÖĞOEÜOZ',
          'OUİPÇFVİ',
          'GYARÇISŞ',
          'JÖĞAVUYM',
          'HKLKĞLEP',
          'ADUGUŞMF',
          'VNÇCEŞTĞ',
        ],
        targetWords: <String>['MEŞE', 'KUŞ', 'YUVA', 'TOPRAK'],
        bonusWords: <String>['GÖLGE'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'orman-yolu-04',
        routeId: 'orman-yolu',
        index: 4,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'OZDERETR',
          'ĞIGBAZOK',
          'VİAÜTEPT',
          'SGİUNGRU',
          'SKOZALAK',
          'ZÖKLMÖKÜ',
          'ĞYDVIGĞĞ',
          'RHJTOĞŞJ',
        ],
        targetWords: <String>['TOPRAK', 'GÖLGE', 'MANTAR', 'KOZALAK', 'DERE'],
        infoCardIds: <String>['orman-info-mantar'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'orman-yolu-05',
        routeId: 'orman-yolu',
        index: 5,
        type: WordHuntLevelType.challenge,
        grid: <String>[
          'SSMIOAOH',
          'DEREPŞKE',
          'LBAFYGOF',
          'ZKLKÇÖZM',
          'OLTAİKAL',
          'ÖİOSÇTLO',
          'LÖYMEUAC',
          'VÖŞĞKPKP',
        ],
        targetWords: <String>['KOZALAK', 'DERE', 'PATİKA', 'ÇİÇEK', 'OTLAR'],
        infoCardIds: <String>['orman-info-kozalak'],
        timeLimitSeconds: 60,
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'orman-yolu-06',
        routeId: 'orman-yolu',
        index: 6,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'ZSÜCNDHO',
          'RAÖMNCTO',
          'KOGKPLLZ',
          'UKAYANEİ',
          'JÜERCOÜI',
          'TFDÇNETI',
          'IGEYİKAD',
          'DVHŞSÇJF',
        ],
        targetWords: <String>['ÇİÇEK', 'OTLAR', 'KAYA', 'SİNCAP'],
        bonusWords: <String>['GEYİK'],
        infoCardIds: <String>['orman-info-sincap'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'orman-yolu-07',
        routeId: 'orman-yolu',
        index: 7,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'GEYİKENŞ',
          'ÇPACNİST',
          'VGPVSÜİS',
          'TDRÇTOYL',
          'AYADJMFP',
          'CĞKLĞYYC',
          'ATÜVEDÖM',
          'ÇİHNNEĞD',
        ],
        targetWords: <String>['SİNCAP', 'GEYİK', 'AĞAÇ', 'YAPRAK', 'DAL'],
        infoCardIds: <String>['orman-info-geyik'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'orman-yolu-08',
        routeId: 'orman-yolu',
        index: 8,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'IRFHIMNİ',
          'GUBHSAHĞ',
          'DMÖÇLLIE',
          'AĞDÇAMUR',
          'PATİKAJE',
          'ŞYPICDDD',
          'ĞPMFKIBĞ',
          'DOEÇYÜZÖ',
        ],
        targetWords: <String>['YAĞMUR', 'ÇAMUR', 'DAMLA', 'DERE', 'PATİKA'],
        bonusWords: <String>['ISLAK'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'orman-yolu-09',
        routeId: 'orman-yolu',
        index: 9,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'LİJEIKTB',
          'AKUYOOTI',
          'OUTNYRŞG',
          'ÖBENEÜBZ',
          'YAALMÖTD',
          'ŞKZPİÇRI',
          'EİIEŞLLH',
          'ĞMFRDDSO',
        ],
        targetWords: <String>['İZLER', 'TÜY', 'TOYNAK', 'YEMİŞ', 'OYUK'],
        bonusWords: <String>['KABUK'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'orman-yolu-10',
        routeId: 'orman-yolu',
        index: 10,
        type: WordHuntLevelType.routeFinal,
        grid: <String>[
          'LMKFĞUMU',
          'TRUİOAYE',
          'RILŞRUZR',
          'ÖLUEMRGP',
          'LNCKAÜVK',
          'ÇALĞNGBM',
          'MCOÜEŞOB',
          'LDYISMKG',
        ],
        targetWords: <String>['ORMAN', 'KEŞİF', 'YOLCULUK', 'CANLI', 'DOĞA', 'UYUM'],
        bonusWords: <String>['MACERA'],
        timeLimitSeconds: 120,
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
    ],
  );
}
