import 'word_hunt_models.dart';

/// Deterministic Content Factory stokundan alınan Orman Yolu içeriği.
///
/// Bu dosya yalnız rota/bölüm verisini taşır. Production katalog açılma
/// kuralı burada tanımlanmaz; `unlockStarsRequired` stok metadata değeridir.
class WordHuntOrmanContent {
  WordHuntOrmanContent._();

  static const List<WordHuntInfoCard> infoCards = <WordHuntInfoCard>[];

  static const WordHuntRouteDefinition ormanYolu = WordHuntRouteDefinition(
    id: 'orman-yolu',
    title: 'Orman Yolu',
    theme: 'orman',
    unlockStarsRequired: 0,
    routeRewardId: 'reward-orman-yolu',
    levels: <WordHuntLevelDefinition>[
      WordHuntLevelDefinition(
        id: 'orman-yolu-01',
        routeId: 'orman-yolu',
        index: 1,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'ŞDKÇLŞVU',
          'UÖAASYIÜ',
          'KŞDĞREİU',
          'EBİASPĞR',
          'AİHORMAN',
          'ÖUMNHLVY',
          'ŞEİGGDHÇ',
          'IZVBLYİÇ',
        ],
        targetWords: <String>['AĞAÇ', 'YAPRAK', 'DAL', 'KÖK', 'ORMAN'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'orman-yolu-02',
        routeId: 'orman-yolu',
        index: 2,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'HÇEUHJÖO',
          'İŞGKÖKNM',
          'EÖUTVÜJL',
          'İŞŞOÜUİN',
          'JKERSARB',
          'VNDMİİYU',
          'NVAAZZRN',
          'UÇKNİÖUS',
        ],
        targetWords: <String>['KÖK', 'ORMAN', 'ÇAM', 'MEŞE', 'KUŞ'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'orman-yolu-03',
        routeId: 'orman-yolu',
        index: 3,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'COSTKİÜS',
          'ÜÖĞOEÜOZ',
          'OUİPÇFVİ',
          'GYARÇISŞ',
          'JÖĞAVUYM',
          'HKLKĞLEP',
          'ADUGUŞMF',
          'VNÇCEŞTĞ',
        ],
        targetWords: <String>['MEŞE', 'KUŞ', 'YUVA', 'TOPRAK'],
        bonusWords: <String>['GÖLGE'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'orman-yolu-04',
        routeId: 'orman-yolu',
        index: 4,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'OZDERETR',
          'ĞIGBAZOK',
          'VİAÜTEPT',
          'SGİUNGRU',
          'SKOZALAK',
          'ZÖKLMÖKÜ',
          'ĞYDVIGĞĞ',
          'RHJTOĞŞJ',
        ],
        targetWords: <String>['TOPRAK', 'GÖLGE', 'MANTAR', 'KOZALAK', 'DERE'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'orman-yolu-05',
        routeId: 'orman-yolu',
        index: 5,
        type: WordHuntLevelType.challenge,
        grid: <String>[
          'SSMIOAOH',
          'DEREPŞKE',
          'LBAFYGOF',
          'ZKLKÇÖZM',
          'OLTAİKAL',
          'ÖİOSÇTLO',
          'LÖYMEUAC',
          'VÖŞĞKPKP',
        ],
        targetWords: <String>['KOZALAK', 'DERE', 'PATİKA', 'ÇİÇEK', 'OTLAR'],
        timeLimitSeconds: 60,
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'orman-yolu-06',
        routeId: 'orman-yolu',
        index: 6,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'ZSÜCNDHO',
          'RAÖMNCTO',
          'KOGKPLLZ',
          'UKAYANEİ',
          'JÜERCOÜI',
          'TFDÇNETI',
          'IGEYİKAD',
          'DVHŞSÇJF',
        ],
        targetWords: <String>['ÇİÇEK', 'OTLAR', 'KAYA', 'SİNCAP'],
        bonusWords: <String>['GEYİK'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'orman-yolu-07',
        routeId: 'orman-yolu',
        index: 7,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'GEYİKENŞ',
          'ÇPACNİST',
          'VGPVSÜİS',
          'TDRÇTOYL',
          'AYADJMFP',
          'CĞKLĞYYC',
          'ATÜVEDÖM',
          'ÇİHNNEĞD',
        ],
        targetWords: <String>['SİNCAP', 'GEYİK', 'AĞAÇ', 'YAPRAK', 'DAL'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'orman-yolu-08',
        routeId: 'orman-yolu',
        index: 8,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'KNZGTŞĞR',
          'BPVVIUNM',
          'FRFÜKÖKÇ',
          'TZODPAAR',
          'HÖHNAMRO',
          'ĞCMÖLÖPD',
          'ĞRJOTYAT',
          'KBİIİLYF',
        ],
        targetWords: <String>['YAPRAK', 'DAL', 'KÖK', 'ORMAN'],
        bonusWords: <String>['ÇAM'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'orman-yolu-09',
        routeId: 'orman-yolu',
        index: 9,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'RÜTAĞCÜĞ',
          'ZŞFJBADA',
          'BĞDĞZĞÜI',
          'IPİİNÇYU',
          'İPYEMİHK',
          'ZKUŞTÇIT',
          'ÜHVEANEC',
          'ÖNAMROKÇ',
        ],
        targetWords: <String>['ORMAN', 'ÇAM', 'MEŞE', 'KUŞ', 'YUVA'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'orman-yolu-10',
        routeId: 'orman-yolu',
        index: 10,
        type: WordHuntLevelType.routeFinal,
        grid: <String>[
          'FKUEGLÖG',
          'FŞÜVJMÖH',
          'ZNİÖAŞİR',
          'ÜÖTNFKUC',
          'FMTOPRAK',
          'VAVUYTDS',
          'RŞOİZBRP',
          'ZYOKÜÇSI',
        ],
        targetWords: <String>['KUŞ', 'YUVA', 'TOPRAK', 'GÖLGE', 'MANTAR'],
        timeLimitSeconds: 120,
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
    ],
  );
}
