import 'word_hunt_models.dart';

class WordHuntStarterContent {
  WordHuntStarterContent._();

  static const List<WordHuntInfoCard> infoCards = <WordHuntInfoCard>[
    WordHuntInfoCard(
      id: 'info-deniz',
      word: 'DENİZ',
      title: 'Deniz',
      shortFact: 'Deniz suyu, çözünmüş tuzlar nedeniyle genellikle tuzludur.',
      category: 'Doğa',
    ),
    WordHuntInfoCard(
      id: 'info-kitap',
      word: 'KİTAP',
      title: 'Kitap',
      shortFact:
          'Kitaplar bilgi, öykü ve fikirleri kalıcı olarak aktarmanın yollarından biridir.',
      category: 'Kültür',
    ),
    WordHuntInfoCard(
      id: 'info-ankara',
      word: 'ANKARA',
      title: 'Ankara',
      shortFact: 'Ankara, Türkiye’nin başkentidir.',
      category: 'Türkiye',
    ),
    WordHuntInfoCard(
      id: 'info-ari',
      word: 'ARI',
      title: 'Arı',
      shortFact: 'Arılar, birçok çiçekli bitkinin tozlaşmasına yardımcı olur.',
      category: 'Doğa',
    ),
    WordHuntInfoCard(
      id: 'info-mars',
      word: 'MARS',
      title: 'Mars',
      shortFact: 'Mars, Güneş’e uzaklık bakımından dördüncü gezegendir.',
      category: 'Uzay',
    ),
    WordHuntInfoCard(
      id: 'info-pusula',
      word: 'PUSULA',
      title: 'Pusula',
      shortFact: 'Pusula, yön bulmaya yardımcı olan bir araçtır.',
      category: 'Keşif',
    ),
  ];

  static const WordHuntRouteDefinition baslangicLimani =
      WordHuntRouteDefinition(
        id: 'baslangic-limani',
        title: 'Başlangıç Limanı',
        theme: 'liman',
        unlockStarsRequired: 18,
        routeRewardId: 'badge-kelime-yolcusu',
        levels: <WordHuntLevelDefinition>[
          WordHuntLevelDefinition(
            id: 'baslangic-1',
            routeId: 'baslangic-limani',
            index: 1,
            type: WordHuntLevelType.normal,
            grid: <String>[
              'BHVFKNÇL',
              'MROTAMBK',
              'GZGBLITÜ',
              'EJÖİEOGS',
              'MEELMASA',
              'ZFOGÖORF',
              'ESTİOYUN',
              'LYUARFCÜ',
            ],
            targetWords: <String>['KALEM', 'MASA', 'OYUN', 'ROTA', 'BİLGİ'],
            bonusWords: <String>['ELMA'],
            starRules: WordHuntStarRules(
              twoStarMaxMistakes: 2,
              threeStarMaxMistakes: 0,
            ),
          ),
          WordHuntLevelDefinition(
            id: 'baslangic-2',
            routeId: 'baslangic-limani',
            index: 2,
            type: WordHuntLevelType.normal,
            grid: <String>[
              'CĞAPİÇCL',
              'MIUGEMİP',
              'PMARTILG',
              'HLÜDBÜHR',
              'EİĞEAÖIF',
              'VMJNTLÜŞ',
              'SAHİLUGÇ',
              'ANJZSLTA',
            ],
            targetWords: <String>['DENİZ', 'GEMİ', 'LİMAN', 'DALGA', 'SAHİL'],
            bonusWords: <String>['MARTI'],
            infoCardIds: <String>['info-deniz'],
            starRules: WordHuntStarRules(
              twoStarMaxMistakes: 2,
              threeStarMaxMistakes: 0,
            ),
          ),
          WordHuntLevelDefinition(
            id: 'baslangic-3',
            routeId: 'baslangic-limani',
            index: 3,
            type: WordHuntLevelType.normal,
            grid: <String>[
              'ŞĞEÖÜNAG',
              'RMDSAUÖĞ',
              'DERSISTS',
              'VLKHONOA',
              'PATİKSIY',
              'OKULNROF',
              'TÜSKÜMFA',
              'ŞNPHHLĞG',
            ],
            targetWords: <String>[
              'KİTAP',
              'OKUL',
              'SINIF',
              'KALEM',
              'DERS',
              'ÖDEV',
            ],
            bonusWords: <String>['SAYFA'],
            infoCardIds: <String>['info-kitap'],
            starRules: WordHuntStarRules(
              twoStarMaxMistakes: 2,
              threeStarMaxMistakes: 0,
            ),
          ),
          WordHuntLevelDefinition(
            id: 'baslangic-4',
            routeId: 'baslangic-limani',
            index: 4,
            type: WordHuntLevelType.normal,
            grid: <String>[
              'GIVJIÇOK',
              'FBLKKĞDF',
              'SMCZUUEŞ',
              'AAZJIDRP',
              'ABIAEHÜÖ',
              'TSDHMCSD',
              'FDKUBAÇF',
              'YIKOŞUNĞ',
            ],
            targetWords: <String>[
              'HIZLI',
              'ZAMAN',
              'SÜRE',
              'HEDEF',
              'ÇABUK',
              'SAAT',
            ],
            bonusWords: <String>['KOŞU'],
            starRules: WordHuntStarRules(
              twoStarMaxMistakes: 2,
              threeStarMaxMistakes: 0,
            ),
          ),
          WordHuntLevelDefinition(
            id: 'baslangic-5',
            routeId: 'baslangic-limani',
            index: 5,
            type: WordHuntLevelType.challenge,
            grid: <String>[
              'ANKARAJB',
              'TÜRKİYEA',
              'OMOVÜAKŞ',
              'ÖÇEGÜNUK',
              'OZZCZILE',
              'KALELTEN',
              'OVFĞZİÜT',
              'ŞEHİRZSÜ',
            ],
            targetWords: <String>[
              'ANKARA',
              'ŞEHİR',
              'TÜRKİYE',
              'BAŞKENT',
              'MECLİS',
              'KULE',
              'KALE',
            ],
            bonusWords: <String>['ANIT'],
            infoCardIds: <String>['info-ankara'],
            timeLimitSeconds: 60,
            starRules: WordHuntStarRules(
              twoStarMaxSeconds: 50,
              threeStarMaxSeconds: 35,
              twoStarMaxMistakes: 1,
              threeStarMaxMistakes: 0,
            ),
          ),
          WordHuntLevelDefinition(
            id: 'baslangic-6',
            routeId: 'baslangic-limani',
            index: 6,
            type: WordHuntLevelType.normal,
            grid: <String>[
              'ŞIIYYNÜG',
              'ÇİÇEKNIK',
              'ÇNŞPAĞAÇ',
              'RİIMRRRİ',
              'LDRYPİPO',
              'ROROAHÇE',
              'YĞTÖYEAN',
              'FAZRÜNKY',
            ],
            targetWords: <String>[
              'DOĞA',
              'ORMAN',
              'AĞAÇ',
              'ÇİÇEK',
              'TOPRAK',
              'YEŞİL',
              'NEHİR',
            ],
            bonusWords: <String>['YAPRAK'],
            starRules: WordHuntStarRules(
              twoStarMaxMistakes: 2,
              threeStarMaxMistakes: 0,
            ),
          ),
          WordHuntLevelDefinition(
            id: 'baslangic-7',
            routeId: 'baslangic-limani',
            index: 7,
            type: WordHuntLevelType.normal,
            grid: <String>[
              'IŞKZNTED',
              'MRBKRİĞO',
              'GHAEAĞOD',
              'RĞLTİNNO',
              'ÇİÇEKAAY',
              'ÇKNPVEŞT',
              'BDPOLENÖ',
              'ÇUKÖSÇNP',
            ],
            targetWords: <String>[
              'ARI',
              'ÇİÇEK',
              'BAL',
              'KOVAN',
              'KANAT',
              'POLEN',
              'PETEK',
              'NEKTAR',
            ],
            bonusWords: <String>['DOĞA'],
            infoCardIds: <String>['info-ari'],
            starRules: WordHuntStarRules(
              twoStarMaxMistakes: 2,
              threeStarMaxMistakes: 0,
            ),
          ),
          WordHuntLevelDefinition(
            id: 'baslangic-8',
            routeId: 'baslangic-limani',
            index: 8,
            type: WordHuntLevelType.normal,
            grid: <String>[
              'ILFEÜCİU',
              'ĞMAÇSDCŞ',
              'ÇHIZSNLO',
              'AGMKUVÇK',
              'İPRYAKVG',
              'VROKSTLO',
              'İÇPTHVÖL',
              'PÇSPÖVÜP',
            ],
            targetWords: <String>[
              'SPOR',
              'TOP',
              'KOŞU',
              'OYUNCU',
              'TAKIM',
              'GOL',
              'MAÇ',
            ],
            bonusWords: <String>['HIZ', 'SKOR'],
            starRules: WordHuntStarRules(
              twoStarMaxMistakes: 2,
              threeStarMaxMistakes: 0,
            ),
          ),
          WordHuntLevelDefinition(
            id: 'baslangic-9',
            routeId: 'baslangic-limani',
            index: 9,
            type: WordHuntLevelType.normal,
            grid: <String>[
              'VGRETARK',
              'NEGEZEGZ',
              'NİKESGÜI',
              'ĞOGUÜNDD',
              'RGYNMÜYL',
              'ÜDETNRAI',
              'UŞZYFÖZY',
              'ÜMARSYUÜ',
            ],
            targetWords: <String>[
              'MARS',
              'UZAY',
              'YILDIZ',
              'GEZEGEN',
              'GÜNEŞ',
              'DÜNYA',
              'UYDU',
              'KRATER',
              'YÖRÜNGE',
            ],
            bonusWords: <String>['ROKET'],
            infoCardIds: <String>['info-mars'],
            starRules: WordHuntStarRules(
              twoStarMaxMistakes: 2,
              threeStarMaxMistakes: 0,
            ),
          ),
          WordHuntLevelDefinition(
            id: 'baslangic-10',
            routeId: 'baslangic-limani',
            index: 10,
            type: WordHuntLevelType.routeFinal,
            grid: <String>[
              'MHEDEFYC',
              'NATPAKAA',
              'FZCYOLTZ',
              'FİLEUİIİ',
              'İNRSRDUG',
              'ŞEUALADL',
              'EPHIFFİİ',
              'KGYDTNIB',
            ],
            targetWords: <String>[
              'PUSULA',
              'YOL',
              'BİLGİ',
              'YILDIZ',
              'HEDEF',
              'KEŞİF',
              'HARİTA',
              'MACERA',
              'KAPTAN',
            ],
            bonusWords: <String>['HAZİNE'],
            infoCardIds: <String>['info-pusula'],
            timeLimitSeconds: 120,
            starRules: WordHuntStarRules(
              twoStarMaxSeconds: 100,
              threeStarMaxSeconds: 75,
              twoStarMaxMistakes: 2,
              threeStarMaxMistakes: 0,
            ),
          ),
        ],
      );
}
