import 'word_hunt_models.dart';

/// Owner-approved locked production content for Kayıp Şehir.
abstract final class WordHuntKayipSehirContent {
  static const List<String> levelNames = <String>[
    'Kervan İzi',
    'Sessiz Kumlar',
    'Gömülü Cephe',
    'Eski Kapı',
    'Fırtına Geçidi',
    'Unutulmuş Çarşı',
    'Sütunlu Avlu',
    'Kurumuş Sarnıç',
    'Kırık Saray',
    'Yeraltı Mührü',
  ];

  static const List<WordHuntInfoCard> infoCards = <WordHuntInfoCard>[
    WordHuntInfoCard(
      id: 'kayip-info-kervan',
      word: 'KERVAN',
      title: 'Kervanlar',
      category: 'Tarih / Ticaret',
      shortFact: 'Kervanlar, uzun yolculuklarda birlikte hareket eden yolcu ve yük gruplarıydı. Özellikle çöl ve ticaret yollarında toplu ilerlemek güvenlik ve taşıma açısından avantaj sağlardı.',
    ),
    WordHuntInfoCard(
      id: 'kayip-info-sutun',
      word: 'SÜTUN',
      title: 'Sütun',
      category: 'Mimari',
      shortFact: 'Sütunlar, tavan ve çatı gibi üst yapıların yükünü taşıyan düşey mimari elemanlardır. Büyük sütun dizileri tarihî yapılarda hem taşıyıcı görev görmüş hem de anıtsal mekânlar oluşturmuştur.',
    ),
    WordHuntInfoCard(
      id: 'kayip-info-revak',
      word: 'REVAK',
      title: 'Revak',
      category: 'Mimari',
      shortFact: 'Revak, genellikle bir yapıya bitişik, üstü örtülü ve önü açık galeri biçimindeki mekândır. Sütun ve kemerlerle kurulan revaklar özellikle sıcak iklimlerde gölgeli alan oluşturur.',
    ),
    WordHuntInfoCard(
      id: 'kayip-info-sarnic',
      word: 'SARNIÇ',
      title: 'Sarnıç',
      category: 'Su Mimarisi',
      shortFact: 'Sarnıç, suyu depolamak için yapılan su geçirmez haznedir ve yağmur suyunun biriktirilmesinde de kullanılabilir. Tarihî sarnıçların iç yüzeylerinde sızıntıyı azaltan özel sıvalara rastlanır.',
    ),
    WordHuntInfoCard(
      id: 'kayip-info-kabartma',
      word: 'KABARTMA',
      title: 'Kabartma Sanatı',
      category: 'Arkeoloji / Sanat',
      shortFact: 'Kabartmada figür veya desenler düz bir yüzeyden yükseliyormuş gibi işlenir ve arka zemine bağlı kalır. Çıkıntının derinliğine göre alçak ve yüksek kabartma gibi türlere ayrılır.',
    ),
    WordHuntInfoCard(
      id: 'kayip-info-muhur',
      word: 'MÜHÜR',
      title: 'Antik Mühürler',
      category: 'Arkeoloji',
      shortFact: 'Antik dünyada mühürler sahiplik ve kimlik belirtmek, kapları kapatmak veya belgeleri doğrulamak için kullanıldı. Mezopotamya’daki silindir mühürler kil üzerinde yuvarlanarak ayrıntılı izler bırakabiliyordu.',
    ),
  ];

  static const WordHuntRouteDefinition kayipSehir =
      WordHuntRouteDefinition(
        id: 'kayip-sehir',
        title: 'Kayıp Şehir',
        theme: 'ancientSeal',
        unlockStarsRequired: 0,
        routeRewardId: 'badge-kayip-sehir-kasifi',
        levels: <WordHuntLevelDefinition>[
      // 1. Kervan İzi
      WordHuntLevelDefinition(
        id: 'kayip-sehir-01',
        routeId: 'kayip-sehir',
        index: 1,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'YÜKSRKSS',
          'SÜVESOMU',
          'TİCARETN',
          'NÇAENVFA',
          'AUIZDKAM',
          'JLİZLERN',
          'LLCLERJN',
          'BUARİĞIJ',
        ],
        targetWords: <String>['KERVAN', 'İZLER', 'ROTA', 'YÜK', 'MENZİL'],
        bonusWords: <String>['TİCARET'],
        infoCardIds: <String>['kayip-info-kervan'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      // 2. Sessiz Kumlar
      WordHuntLevelDefinition(
        id: 'kayip-sehir-02',
        routeId: 'kayip-sehir',
        index: 2,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'TŞÖYEZÜY',
          'MYRURNÜA',
          'BBUÜOÜİJ',
          'KÜÖNZYKŞ',
          'IUBCYGHT',
          'ZAMYOFÂO',
          'ĞRKUNÜFR',
          'DÜOGLTUS',
        ],
        targetWords: <String>['KUM', 'KUMUL', 'RÜZGÂR', 'OYMA', 'YÜZEY'],
        bonusWords: <String>['EROZYON'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      // 3. Gömülü Cephe
      WordHuntLevelDefinition(
        id: 'kayip-sehir-03',
        routeId: 'kayip-sehir',
        index: 3,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'EHPECÜLJ',
          'OGİDIKAU',
          'AINUTÜSS',
          'LGÇVNZBP',
          'MPDAICŞĞ',
          'IGÇRLÜTÇ',
          'FÜİRAMİM',
          'REMEKZĞU',
        ],
        targetWords: <String>['CEPHE', 'SÜTUN', 'KEMER', 'DUVAR', 'KALINTI'],
        bonusWords: <String>['MİMARİ'],
        infoCardIds: <String>['kayip-info-sutun'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      // 4. Eski Kapı
      WordHuntLevelDefinition(
        id: 'kayip-sehir-04',
        routeId: 'kayip-sehir',
        index: 4,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'KTİÇEGOS',
          'AHVELİUÖ',
          'PYTLŞRİS',
          'IĞIUEİFÜ',
          'PAŞKBŞKH',
          'FMAÇPNMH',
          'ÜPLLĞGÇÇ',
          'JCUDEÜFO',
        ],
        targetWords: <String>['KAPI', 'EŞİK', 'SUR', 'LEVHA', 'KULE'],
        bonusWords: <String>['GEÇİT', 'GİRİŞ'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      // 5. Fırtına Geçidi
      WordHuntLevelDefinition(
        id: 'kayip-sehir-05',
        routeId: 'kayip-sehir',
        index: 5,
        type: WordHuntLevelType.challenge,
        grid: <String>[
          'HÜŞFLISD',
          'EFIRTINA',
          'DTOIĞMLŞ',
          'EEJICURŞ',
          'FRNİSTÜK',
          'HAPURRTG',
          'KŞPHÖOUR',
          'OİEGZHIJ',
        ],
        targetWords: <String>['FIRTINA', 'PUSULA', 'GÖRÜŞ', 'HEDEF', 'SIĞINAK', 'İŞARET'],
        bonusWords: <String>['TOZ', 'HORTUM'],
        timeLimitSeconds: 60,
        starRules: WordHuntStarRules(
          twoStarMaxSeconds: 50,
          threeStarMaxSeconds: 35,
          twoStarMaxMistakes: 1,
          threeStarMaxMistakes: 0,
        ),
      ),
      // 6. Unutulmuş Çarşı
      WordHuntLevelDefinition(
        id: 'kayip-sehir-06',
        routeId: 'kayip-sehir',
        index: 6,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'MZŞĞÜPMD',
          'ŞIHHNSTL',
          'İŞIAMEÜR',
          'BRONZRCS',
          'CAEGFACN',
          'EÇÂKUMAŞ',
          'LHHYPİRV',
          'PADYNKZM',
        ],
        targetWords: <String>['ÇARŞI', 'TEZGÂH', 'TÜCCAR', 'BRONZ', 'KUMAŞ'],
        bonusWords: <String>['SERAMİK'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      // 7. Sütunlu Avlu
      WordHuntLevelDefinition(
        id: 'kayip-sehir-07',
        routeId: 'kayip-sehir',
        index: 7,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'İJAUNSTO',
          'ŞJZAKAZÜ',
          'LAUKEÇYU',
          'EUJKRAAU',
          'MOZAİKLF',
          'EOŞVDVDH',
          'LKZEACID',
          'ICMRCIZS',
        ],
        targetWords: <String>['AVLU', 'REVAK', 'DİREK', 'SAÇAK', 'İŞLEME', 'MOZAİK'],
        bonusWords: <String>['YALDIZ'],
        infoCardIds: <String>['kayip-info-revak'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      // 8. Kurumuş Sarnıç
      WordHuntLevelDefinition(
        id: 'kayip-sehir-08',
        routeId: 'kayip-sehir',
        index: 8,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'ÜVMBZRAE',
          'ÜTSKULOĞ',
          'ZPOAUBNG',
          'ÇĞÇRRYDS',
          'ZAAUTNUĞ',
          'DRRKAUIG',
          'KMFLIÇVÇ',
          'RNNHLŞİÇ',
        ],
        targetWords: <String>['SARNIÇ', 'ARK', 'AKIŞ', 'KUYU', 'OLUK', 'TORTU'],
        bonusWords: <String>['KURAK'],
        infoCardIds: <String>['kayip-info-sarnic'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      // 9. Kırık Saray
      WordHuntLevelDefinition(
        id: 'kayip-sehir-09',
        routeId: 'kayip-sehir',
        index: 9,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'JRFRESKG',
          'BYUTEBAM',
          'RPMYFLBİ',
          'ADOAETAN',
          'EATRRMRŞ',
          'ÇMİAMBTT',
          'DGFSAMMŞ',
          'PAİBNVAO',
        ],
        targetWords: <String>['SARAY', 'MOTİF', 'KABARTMA', 'DAMGA', 'GALERİ', 'MABET'],
        bonusWords: <String>['FRESK', 'FERMAN'],
        infoCardIds: <String>['kayip-info-kabartma'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      // 10. Yeraltı Mührü
      WordHuntLevelDefinition(
        id: 'kayip-sehir-10',
        routeId: 'kayip-sehir',
        index: 10,
        type: WordHuntLevelType.routeFinal,
        grid: <String>[
          'ÇŞDCNJTY',
          'IŞİYESIR',
          'ÇTDNVLCA',
          'ESLNİODT',
          'MÜÇADBUH',
          'BRKFRMLA',
          'EGAEEEHN',
          'RÜHÜMSYA',
        ],
        targetWords: <String>['MÜHÜR', 'SEMBOL', 'SÜRGÜ', 'ÇEMBER', 'MERDİVEN', 'YERALTI', 'SIR'],
        bonusWords: <String>['ANAHTAR', 'İNİŞ'],
        infoCardIds: <String>['kayip-info-muhur'],
        timeLimitSeconds: 120,
        starRules: WordHuntStarRules(
          twoStarMaxSeconds: 80,
          threeStarMaxSeconds: 60,
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
        ],
      );
}
