import 'word_hunt_models.dart';

/// Owner-approved locked production content for Yeraltı Krallığı.
abstract final class WordHuntYeraltiKralligiContent {
  static const List<String> levelNames = <String>[
    'Gizli İniş',
    'Taş Damarlar',
    'Derin Sarnıç',
    'Bakır Kanallar',
    'Halka Kilidi',
    'Taş Mekanizma',
    'Gömülü Salon',
    'Anıt Odası',
    'Kraliyet Hazinesi',
    'Göksel Mühür',
  ];

  static const List<WordHuntInfoCard> infoCards = <WordHuntInfoCard>[
    WordHuntInfoCard(
      id: 'yeralti-info-dehliz',
      word: 'DEHLİZ',
      title: 'Dehliz',
      category: 'Mimari',
      shortFact: 'Dehliz, üstü kapalı, dar ve uzun geçit anlamına gelir. Yapıların farklı bölümlerini birbirine bağlayan koridor benzeri mekânlar için kullanılabilir.',
    ),
    WordHuntInfoCard(
      id: 'yeralti-info-tonoz',
      word: 'TONOZ',
      title: 'Tonoz',
      category: 'Mimari',
      shortFact: 'Tonoz, bir mekânı taş veya tuğlayla kemerli biçimde örten mimari örtüdür. En basit türlerinden beşik tonoz, uzatılmış bir kemer gibi düşünülebilir.',
    ),
    WordHuntInfoCard(
      id: 'yeralti-info-bakir',
      word: 'BAKIR',
      title: 'Bakır',
      category: 'Malzeme / Teknoloji',
      shortFact: 'Bakır kolay şekillenen, ısıyı ve elektriği iyi ileten bir metaldir. Kalayla alaşımlandığında tarih boyunca yaygın biçimde kullanılan bronz elde edilir.',
    ),
    WordHuntInfoCard(
      id: 'yeralti-info-mihver',
      word: 'MİHVER',
      title: 'Mihver',
      category: 'Mekanik',
      shortFact: 'Mihver, bir cismin veya parçanın çevresinde döndüğü ekseni anlatan bir terimdir. Çark ve kasnak gibi dönen parçaların hareketini tanımlarken dönüş eksenini belirtmek için kullanılabilir.',
    ),
    WordHuntInfoCard(
      id: 'yeralti-info-kitabe',
      word: 'KİTABE',
      title: 'Kitabeler',
      category: 'Arkeoloji / Epigrafi',
      shortFact: 'Kitabeler, taş veya metal gibi dayanıklı yüzeylere yazılmış tarihî yazıtlardır. Adlar, tarihler, unvanlar ve olaylar hakkında bilgi taşıdıkları için tarih araştırmalarında önemli kaynaklardır.',
    ),
    WordHuntInfoCard(
      id: 'yeralti-info-usturlap',
      word: 'USTURLAP',
      title: 'Usturlap',
      category: 'Astronomi / Teknoloji',
      shortFact: 'Usturlap, gökyüzünü düzlem üzerinde modelleyen tarihî bir astronomi aracıdır. Güneş ve yıldızların konumlarından yararlanarak zaman, yön ve göksel ölçümlerle ilgili hesaplar yapılabilir.',
    ),
  ];

  static const WordHuntRouteDefinition yeraltiKralligi =
      WordHuntRouteDefinition(
        id: 'yeralti-kralligi',
        title: 'Yeraltı Krallığı',
        theme: 'mechanicalSeal',
        unlockStarsRequired: 0,
        routeRewardId: 'badge-yeralti-kasifi',
        levels: <WordHuntLevelDefinition>[
      // 1. Gizli İniş
      WordHuntLevelDefinition(
        id: 'yeralti-kralligi-01',
        routeId: 'yeralti-kralligi',
        index: 1,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'GJZİNİŞU',
          'YMFİRÜAJ',
          'TKRULOME',
          'UEUEBHLM',
          'DBGLGAEE',
          'CAFFŞMFD',
          'VĞEEÇOEA',
          'VSMAĞFLK',
        ],
        targetWords: <String>['İNİŞ', 'DEHLİZ', 'DERİN', 'MEŞALE', 'KADEME'],
        bonusWords: <String>['LOŞLUK'],
        infoCardIds: <String>['yeralti-info-dehliz'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      // 2. Taş Damarlar
      WordHuntLevelDefinition(
        id: 'yeralti-kralligi-02',
        routeId: 'yeralti-kralligi',
        index: 2,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'YPÖRCİRÜ',
          'KNĞNCBÖÇ',
          'DÖSYPCŞZ',
          'ZAKTÜNEL',
          'AHMUİBBJ',
          'CLKAYAEK',
          'RODİROKK',
          'DHİTMDEK',
        ],
        targetWords: <String>['TÜNEL', 'ŞEBEKE', 'OYUK', 'KAYA', 'DAMAR'],
        bonusWords: <String>['KORİDOR'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      // 3. Derin Sarnıç
      WordHuntLevelDefinition(
        id: 'yeralti-kralligi-03',
        routeId: 'yeralti-kralligi',
        index: 3,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'TBOĞAEOJ',
          'UZAZSBÇT',
          'HAÇOİACİ',
          'AKINTIGL',
          'ZANOJBHI',
          'NVRTİPFZ',
          'EAAPAYEO',
          'CSSSSZOF',
        ],
        targetWords: <String>['SARNIÇ', 'AKINTI', 'TONOZ', 'PAYE', 'HAZNE'],
        bonusWords: <String>['SAVAK'],
        infoCardIds: <String>['yeralti-info-tonoz'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      // 4. Bakır Kanallar
      WordHuntLevelDefinition(
        id: 'yeralti-kralligi-04',
        routeId: 'yeralti-kralligi',
        index: 4,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'IDŞÖACBK',
          'LPPMĞNZK',
          'DAJİBUAM',
          'AÖCTUNUV',
          'DSÖEAEKU',
          'MDBLCHRD',
          'ĞYGİOOUV',
          'RIKABZTR',
        ],
        targetWords: <String>['BAKIR', 'KANAL', 'HAT', 'VANA', 'BORU'],
        bonusWords: <String>['İLETİM', 'TURKUAZ'],
        infoCardIds: <String>['yeralti-info-bakir'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      // 5. Halka Kilidi
      WordHuntLevelDefinition(
        id: 'yeralti-kralligi-05',
        routeId: 'yeralti-kralligi',
        index: 5,
        type: WordHuntLevelType.challenge,
        grid: <String>[
          'SIRAKLAH',
          'YÖKYEKİİ',
          'NKİTNEÇH',
          'ŞİFREÖUH',
          'PLHIZĞMO',
          'ĞİIŞÜNÖD',
          'ITMPDBDZ',
          'IÜEHKBUU',
        ],
        targetWords: <String>['HALKA', 'KİLİT', 'DÜZENEK', 'ŞİFRE', 'DÖNÜŞ', 'SIRA'],
        bonusWords: <String>['ÇENTİK', 'PİM'],
        timeLimitSeconds: 60,
        starRules: WordHuntStarRules(
          twoStarMaxSeconds: 45,
          threeStarMaxSeconds: 30,
          twoStarMaxMistakes: 1,
          threeStarMaxMistakes: 0,
        ),
      ),
      // 6. Taş Mekanizma
      WordHuntLevelDefinition(
        id: 'yeralti-kralligi-06',
        routeId: 'yeralti-kralligi',
        index: 6,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'VOKĞRÇOC',
          'SSOAFCVJ',
          'LMLĞNHAR',
          'ĞİZIDSBD',
          'MHARAKAM',
          'VVBLŞĞYK',
          'JEJIŞRCD',
          'MRİKMEUÇ',
        ],
        targetWords: <String>['KASNAK', 'MİL', 'KOL', 'AĞIRLIK', 'MİHVER'],
        bonusWords: <String>['MAKARA'],
        infoCardIds: <String>['yeralti-info-mihver'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      // 7. Gömülü Salon
      WordHuntLevelDefinition(
        id: 'yeralti-kralligi-07',
        routeId: 'yeralti-kralligi',
        index: 7,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'YİVZHĞÇİ',
          'FÇĞEMNSM',
          'RLYACMİA',
          'IEKÜRSÜZ',
          'TAEKABUL',
          'MTZRCJÇA',
          'ŞMELBMAO',
          'LMİUTGİR',
        ],
        targetWords: <String>['KABUL', 'MERASİM', 'AMBLEM', 'MAKAM', 'KÜRSÜ', 'HEYET'],
        bonusWords: <String>['ELÇİ'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      // 8. Anıt Odası
      WordHuntLevelDefinition(
        id: 'yeralti-kralligi-08',
        routeId: 'yeralti-kralligi',
        index: 8,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'BCĞHLBYT',
          'KOTKMŞEİ',
          'PİBTARİH',
          'SUTNOYPT',
          'TIZAYCIG',
          'EGLEBNÖT',
          'ÜAYŞAEAV',
          'MEYİÜŞÜB',
        ],
        targetWords: <String>['ANIT', 'KİTABE', 'YAZIT', 'YONTU', 'TARİH', 'BELGE'],
        bonusWords: <String>['KAYIT'],
        infoCardIds: <String>['yeralti-info-kitabe'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      // 9. Kraliyet Hazinesi
      WordHuntLevelDefinition(
        id: 'yeralti-kralligi-09',
        routeId: 'yeralti-kralligi',
        index: 9,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'GYBİLGİZ',
          'ÜKIDNASL',
          'KEÇLÖAPT',
          'HAZİNEEZ',
          'USTURLAP',
          'ORGGBJIP',
          'ŞĞEAÇBUI',
          'ALTINJEO',
        ],
        targetWords: <String>['HAZİNE', 'ALTIN', 'TABLET', 'PERGEL', 'USTURLAP', 'ÖLÇEK'],
        bonusWords: <String>['BİLGİ', 'SANDIK'],
        infoCardIds: <String>['yeralti-info-usturlap'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      // 10. Göksel Mühür
      WordHuntLevelDefinition(
        id: 'yeralti-kralligi-10',
        routeId: 'yeralti-kralligi',
        index: 10,
        type: WordHuntLevelType.routeFinal,
        grid: <String>[
          'GÖVŞGKPM',
          'ÜÖUĞODÜU',
          'NNKZTHAN',
          'EBASÜTEO',
          'ŞÇVREUŞK',
          'ÖUZIDLIY',
          'MBURÇAPF',
          'BİPUCUKĞ',
        ],
        targetWords: <String>['GÖKSEL', 'MÜHÜR', 'GÜNEŞ', 'DOĞU', 'BURÇ', 'KONUM', 'YILDIZ'],
        bonusWords: <String>['İPUCU', 'KADRAN'],
        timeLimitSeconds: 120,
        starRules: WordHuntStarRules(
          twoStarMaxSeconds: 75,
          threeStarMaxSeconds: 55,
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
        ],
      );
}
