import 'word_hunt_models.dart';

class WordHuntStarterContent {
  WordHuntStarterContent._();

  static const List<WordHuntInfoCard> infoCards = <WordHuntInfoCard>[
    WordHuntInfoCard(
      id: 'info-deniz',
      word: 'DENİZ',
      title: 'Deniz',
      shortFact: 'Deniz suyu, çözünmüş tuzlar nedeniyle genellikle tuzludur.',
      category: 'Doğa',
    ),
    WordHuntInfoCard(
      id: 'info-kitap',
      word: 'KİTAP',
      title: 'Kitap',
      shortFact:
          'Kitaplar bilgi, öykü ve fikirleri kalıcı olarak aktarmanın yollarından biridir.',
      category: 'Kültür',
    ),
    WordHuntInfoCard(
      id: 'info-ankara',
      word: 'ANKARA',
      title: 'Ankara',
      shortFact: 'Ankara, Türkiye’nin başkentidir.',
      category: 'Türkiye',
    ),
    WordHuntInfoCard(
      id: 'info-ari',
      word: 'ARI',
      title: 'Arı',
      shortFact: 'Arılar, birçok çiçekli bitkinin tozlaşmasına yardımcı olur.',
      category: 'Doğa',
    ),
    WordHuntInfoCard(
      id: 'info-mars',
      word: 'MARS',
      title: 'Mars',
      shortFact: 'Mars, Güneş’e uzaklık bakımından dördüncü gezegendir.',
      category: 'Uzay',
    ),
    WordHuntInfoCard(
      id: 'info-pusula',
      word: 'PUSULA',
      title: 'Pusula',
      shortFact: 'Pusula, yön bulmaya yardımcı olan bir araçtır.',
      category: 'Keşif',
    ),
  ];

  static const WordHuntRouteDefinition
  baslangicLimani = WordHuntRouteDefinition(
    id: 'baslangic-limani',
    title: 'Başlangıç Limanı',
    theme: 'liman',
    unlockStarsRequired: 18,
    routeRewardId: 'badge-kelime-yolcusu',
    plannedLevelCount: 100,
    segments: <WordHuntSegmentDefinition>[
      WordHuntSegmentDefinition(
        id: 'baslangic-limani-segment-01',
        index: 1,
        displayName: 'Segment 1',
        startLevelIndex: 1,
        endLevelIndex: 10,
      ),
      WordHuntSegmentDefinition(
        id: 'baslangic-limani-segment-02',
        index: 2,
        displayName: 'Segment 2',
        startLevelIndex: 11,
        endLevelIndex: 20,
      ),
      WordHuntSegmentDefinition(
        id: 'baslangic-limani-segment-03',
        index: 3,
        displayName: 'Segment 3',
        startLevelIndex: 21,
        endLevelIndex: 30,
      ),
      WordHuntSegmentDefinition(
        id: 'baslangic-limani-segment-04',
        index: 4,
        displayName: 'Fener Burnu',
        startLevelIndex: 31,
        endLevelIndex: 40,
      ),
    ],
    levels: <WordHuntLevelDefinition>[
      WordHuntLevelDefinition(
        id: 'baslangic-1',
        routeId: 'baslangic-limani',
        index: 1,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'EGVRPBĞK',
          'LNVPOİÜH',
          'MSCMYLSE',
          'ACFAUGİV',
          'MHÜSNİLF',
          'CLOABÖGĞ',
          'KALEMGİB',
          'SLJROTAG',
        ],
        targetWords: <String>['KALEM', 'MASA', 'OYUN', 'ROTA', 'BİLGİ', 'SİLGİ'],
        bonusWords: <String>['ELMA'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-2',
        routeId: 'baslangic-limani',
        index: 2,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'DLİMANON',
          'ENVSAHİL',
          'NCMARTIĞ',
          'İDKİEAKC',
          'ZACÖİDZS',
          'ALKÜREKD',
          'ÇGKGEMİN',
          'ŞAOKLIHG',
        ],
        targetWords: <String>['DENİZ', 'GEMİ', 'LİMAN', 'DALGA', 'SAHİL', 'KÜREK'],
        bonusWords: <String>['MARTI'],
        infoCardIds: <String>['info-deniz'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-3',
        routeId: 'baslangic-limani',
        index: 3,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'ŞĞEÖÜNAG',
          'RMDSAUKĞ',
          'DERSISAS',
          'VLKHONĞA',
          'PATİKSIY',
          'OKULNRTF',
          'TÜSKÜMFA',
          'ŞNPHHLĞG',
        ],
        targetWords: <String>[
          'KİTAP',
          'OKUL',
          'SINIF',
          'KAĞIT',
          'DERS',
          'ÖDEV',
        ],
        bonusWords: <String>['SAYFA'],
        infoCardIds: <String>['info-kitap'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-4',
        routeId: 'baslangic-limani',
        index: 4,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'GIVJIÇOK',
          'FBLKKĞDF',
          'SMCZUUEŞ',
          'AAZJIDRP',
          'ABIAEHÜÖ',
          'TSDHMCSD',
          'FDKUBAÇF',
          'YIKOŞUNĞ',
        ],
        targetWords: <String>[
          'HIZLI',
          'ZAMAN',
          'SÜRE',
          'HEDEF',
          'ÇABUK',
          'SAAT',
        ],
        bonusWords: <String>['KOŞU'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-5',
        routeId: 'baslangic-limani',
        index: 5,
        type: WordHuntLevelType.challenge,
        grid: <String>[
          'BZAPTİKÖ',
          'AĞNUÜÖUD',
          'ŞUKLRHLM',
          'KŞACKĞEE',
          'EERÇİRJC',
          'NHAIYRGL',
          'TİGİEARİ',
          'CRÜANITS',
        ],
        targetWords: <String>[
          'ANKARA',
          'ŞEHİR',
          'TÜRKİYE',
          'BAŞKENT',
          'MECLİS',
          'KULE',
        ],
        bonusWords: <String>['ANIT'],
        infoCardIds: <String>['info-ankara'],
        timeLimitSeconds: 60,
        starRules: WordHuntStarRules(
          twoStarMaxSeconds: 50,
          threeStarMaxSeconds: 35,
          twoStarMaxMistakes: 1,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-6',
        routeId: 'baslangic-limani',
        index: 6,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'ŞIIYYNÜG',
          'ÇİÇEKNIK',
          'ÇNŞPAĞAÇ',
          'RİIMRRRİ',
          'LDRYPİPO',
          'ROROAHÇE',
          'YĞTÖYEAN',
          'FAZRÜNKY',
        ],
        targetWords: <String>[
          'DOĞA',
          'ORMAN',
          'AĞAÇ',
          'ÇİÇEK',
          'TOPRAK',
          'YEŞİL',
          'NEHİR',
        ],
        bonusWords: <String>['YAPRAK'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-7',
        routeId: 'baslangic-limani',
        index: 7,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'ĞGARIBAL',
          'ÇAYIRIÇP',
          'POLENPCE',
          'KMEYVEFT',
          'SAKOVANE',
          'EJNEZSKK',
          'IHNAMUOV',
          'BSZOTNJK',
        ],
        targetWords: <String>[
          'ARI',
          'MEYVE',
          'BAL',
          'KOVAN',
          'KANAT',
          'POLEN',
          'PETEK',
        ],
        bonusWords: <String>['ÇAYIR'],
        infoCardIds: <String>['info-ari'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-8',
        routeId: 'baslangic-limani',
        index: 8,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'HIİFTOPS',
          'ÇSETAEŞK',
          'MKPAAUJO',
          'ANLOĞKLR',
          'ÇYUYRİIV',
          'DOYUNCUM',
          'UGOLDÖYÜ',
          'JİÇHIZMR',
        ],
        targetWords: <String>[
          'SPOR',
          'TOP',
          'FAUL',
          'OYUNCU',
          'TAKIM',
          'GOL',
          'MAÇ',
        ],
        bonusWords: <String>['HIZ', 'SKOR'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-9',
        routeId: 'baslangic-limani',
        index: 9,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'DÜNYAFAĞ',
          'GRKMUUGY',
          'CEKMĞZFI',
          'UİZRAKYL',
          'ZKUEORMD',
          'ANNYGKSI',
          'YOMMDEEZ',
          'GÜNEŞUNT',
        ],
        targetWords: <String>[
          'MARS',
          'UZAY',
          'YILDIZ',
          'GEZEGEN',
          'GÜNEŞ',
          'DÜNYA',
          'UYDU',
        ],
        bonusWords: <String>['ROKET'],
        infoCardIds: <String>['info-mars'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-10',
        routeId: 'baslangic-limani',
        index: 10,
        type: WordHuntLevelType.routeFinal,
        grid: <String>[
          'ÖFHARİTA',
          'YPUSULAT',
          'İOMACERA',
          'FÖLİAEÇK',
          'ÇKAPTANE',
          'BİUŞAMCŞ',
          'HAZİNEFİ',
          'DİPUCUJF',
        ],
        targetWords: <String>[
          'PUSULA',
          'YOL',
          'İPUCU',
          'KEŞİF',
          'HARİTA',
          'MACERA',
          'KAPTAN',
        ],
        bonusWords: <String>['HAZİNE'],
        infoCardIds: <String>['info-pusula'],
        timeLimitSeconds: 120,
        starRules: WordHuntStarRules(
          twoStarMaxSeconds: 100,
          threeStarMaxSeconds: 75,
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-11',
        routeId: 'baslangic-limani',
        index: 11,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'RIKLÖŞFT',
          'EOAHFJUM',
          'NHDĞÇLÜG',
          'KRRFUAHB',
          'KAABÖUTP',
          'VVBKAPII',
          'AUANADİF',
          'RDÜRPÖKB',
        ],
        targetWords: <String>['BARDAK', 'KÖPRÜ', 'BULUT', 'RENK', 'KAPI', 'DUVAR', 'ÇATI'],
        bonusWords: <String>['FİDAN'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 3,
          threeStarMaxMistakes: 1,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-12',
        routeId: 'baslangic-limani',
        index: 12,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'SESGKUOS',
          'HEKİERVO',
          'ÖEZMDMNI',
          'AÜĞÇEUPK',
          'MÜAAFKŞR',
          'DVTNTJYA',
          'KÖOTEPĞŞ',
          'ZMNAROTR',
        ],
        targetWords: <String>['ÇANTA', 'MÜZİK', 'KUMRU', 'DEFTER', 'NOTA', 'ŞARKI', 'SES'],
        bonusWords: <String>['DÜĞME'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 3,
          threeStarMaxMistakes: 1,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-13',
        routeId: 'baslangic-limani',
        index: 13,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'ÇİLEKÜOP',
          'MEBAHÇEY',
          'KIEYINİN',
          'AIKDUTDE',
          'FŞTBRHEM',
          'CZASHEKİ',
          'ASÜIAIPÇ',
          'ZARİKYLĞ',
        ],
        targetWords: <String>['BAHÇE', 'KEDİ', 'PERDE', 'SABUN', 'YASTIK', 'ÇİMEN', 'ÇİLEK'],
        bonusWords: <String>['KİRAZ'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 3,
          threeStarMaxMistakes: 1,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-14',
        routeId: 'baslangic-limani',
        index: 14,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'BNOGAVZY',
          'TARAKÜJE',
          'PPENCERE',
          'AĞRGMBÖI',
          'RMUİAÜKM',
          'ONÖMCİZG',
          'ÇGBURNMÜ',
          'DUSENKİO',
        ],
        targetWords: <String>['VAGON', 'BAMBU', 'İNCİR', 'TARAK', 'PENCERE', 'ERİK', 'ÜZÜM'],
        bonusWords: <String>['ÇORAP'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-15',
        routeId: 'baslangic-limani',
        index: 15,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'FMIĞHNKN',
          'AEYEAÜUU',
          'NRCIVBMV',
          'RDLCURSA',
          'UİÖUZÜAK',
          'TVÇCVDLĞ',
          'İEKLVAKC',
          'MNIYIKBD',
        ],
        targetWords: <String>['KUMSAL', 'TURNA', 'BAVUL', 'KAVUN', 'MERDİVEN', 'KIYI', 'HAVUZ'],
        bonusWords: <String>['DÜRBÜN'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-16',
        routeId: 'baslangic-limani',
        index: 16,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'KEMANVPL',
          'SREÜNKDK',
          'AADNAMUK',
          'KAIHVZFE',
          'AKHBİIES',
          'MPMERCAN',
          'HAGÇAYOB',
          'TŞARESİM',
        ],
        targetWords: <String>['MERCAN', 'ŞAPKA', 'MAKAS', 'KEMAN', 'KUMANDA', 'RESİM', 'BOYA'],
        bonusWords: <String>['FIRÇA'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-17',
        routeId: 'baslangic-limani',
        index: 17,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'NİTYEZÖB',
          'ECOBÇEKO',
          'USNAEJAY',
          'LŞAZKVRE',
          'YİYKMZML',
          'CŞİKEUUK',
          'CEPVCMTE',
          'BJHTEĞKN',
        ],
        targetWords: <String>['ZEYTİN', 'ARMUT', 'ÇEKMECE', 'PİYANO', 'ŞİŞE', 'MUZ', 'KASE'],
        bonusWords: <String>['YELKEN'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-18',
        routeId: 'baslangic-limani',
        index: 18,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'ZUPRAKĞZ',
          'JNOBKPSİ',
          'ÜRJJAÇRV',
          'ÖRDEKDZE',
          'KESTANEC',
          'BKAZAKLM',
          'TELKİSİB',
          'TENCEREP',
        ],
        targetWords: <String>[
          'KARPUZ',
          'TENCERE',
          'ÖRDEK',
          'BİSİKLET',
          'CEVİZ',
          'KESTANE',
          'BADEM',
        ],
        bonusWords: <String>['KAZAK'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-19',
        routeId: 'baslangic-limani',
        index: 19,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'YGSKÖMÜR',
          'FŞAİİEIF',
          'İKNDKLEÇ',
          'IADUANHA',
          'SYAHEGTN',
          'KALRHHİU',
          'AKYFABGD',
          'SÖETAHKO',
        ],
        targetWords: <String>['FENER', 'SAKSI', 'KAYAK', 'HALI', 'SANDALYE', 'ODUN', 'TAHTA'],
        bonusWords: <String>['KÖMÜR'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-20',
        routeId: 'baslangic-limani',
        index: 20,
        type: WordHuntLevelType.challenge,
        grid: <String>[
          'LAKATROP',
          'MKASABAÖ',
          'BAMANDAL',
          'DDCJKÖYF',
          'PANTOLON',
          'ŞEMSİYED',
          'ÇEKİRDEK',
          'ĞMUTÜSPB',
        ],
        targetWords: <String>[
          'PANTOLON',
          'PORTAKAL',
          'ŞEMSİYE',
          'KASABA',
          'ÇEKİRDEK',
          'SÜT',
          'CAM',
          'KÖY',
        ],
        bonusWords: <String>['MANDAL'],
        timeLimitSeconds: 120,
        starRules: WordHuntStarRules(
          twoStarMaxSeconds: 100,
          threeStarMaxSeconds: 75,
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-21',
        routeId: 'baslangic-limani',
        index: 21,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'KABATEÇY',
          'KUPAZANR',
          'ÇLİİRYEM',
          'ATVŞODAÖ',
          'TAARNBET',
          'AFGİMBYU',
          'LAMAIRÜB',
          'NÜLYATAK',
        ],
        targetWords: <String>['AVİZE', 'TABAK', 'ÇATAL', 'YORGAN', 'LAMBA', 'ÇARŞAF', 'YATAK', 'MİNDER'],
        bonusWords: <String>['KUPA'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 3,
          threeStarMaxMistakes: 1,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-22',
        routeId: 'baslangic-limani',
        index: 22,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'RLDHAVLU',
          'KEAKİLİM',
          'UÖGVŞUDİ',
          'TBYNAJÜD',
          'LAKRÜBÖO',
          'OZKPBSOL',
          'KKULSUMA',
          'OYNABKFP',
        ],
        targetWords: <String>['KOLTUK', 'DOLAP', 'HAVLU', 'BANYO', 'LAVABO', 'MUSLUK', 'DUŞ', 'KİLİM'],
        bonusWords: <String>['SÜNGER'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 3,
          threeStarMaxMistakes: 1,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-23',
        routeId: 'baslangic-limani',
        index: 23,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'AORTEMİS',
          'ĞYÜSESÜV',
          'GAPIKBAR',
          'DVÖAOPBÖ',
          'UMTTUİBF',
          'RAORLUGO',
          'ARSEŞDÜŞ',
          'KTTTRENJ',
        ],
        targetWords: <String>['OTOBÜS', 'TAKSİ', 'DURAK', 'BİLET', 'ŞOFÖR', 'TREN', 'TRAMVAY', 'METRO'],
        bonusWords: <String>['VAPUR'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-24',
        routeId: 'baslangic-limani',
        index: 24,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'DMGTTFIS',
          'AIZİRRĞZ',
          'KAJMUİAP',
          'KASİĞNYO',
          'EEŞSOYEĞ',
          'RTMIYERA',
          'ÖEÜKKPEÇ',
          'ÇREÇELTA',
        ],
        targetWords: <String>['EKMEK', 'PEYNİR', 'YOĞURT', 'REÇEL', 'ÇÖREK', 'SİMİT', 'POĞAÇA', 'TEREYAĞI'],
        bonusWords: <String>['KAŞIK'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-25',
        routeId: 'baslangic-limani',
        index: 25,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'GEPARATS',
          'İCRMGDET',
          'NKÜÜCPKE',
          'DUÜŞEÇİK',
          'İÇRTKTTR',
          'RÜÜEŞAEA',
          'İĞNRİMSM',
          'MKAİFZAA',
        ],
        targetWords: <String>['MARKET', 'SEPET', 'KASA', 'PARA', 'FİŞ', 'ÜRÜN', 'İNDİRİM', 'MÜŞTERİ'],
        bonusWords: <String>['ETİKET'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-26',
        routeId: 'baslangic-limani',
        index: 26,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'ĞIKEŞMİŞ',
          'FOTNMBPG',
          'IRUMĞAYF',
          'RKKIRAĞI',
          'TZRAGZÜR',
          'ISAĞANAK',
          'NIİYDOLU',
          'ALISAHPM',
        ],
        targetWords: <String>[
          'RÜZGAR',
          'DOLU',
          'KIRAĞI',
          'ŞİMŞEK',
          'SAĞANAK',
          'YAĞMUR',
          'SİS',
          'FIRTINA',
        ],
        bonusWords: <String>['AYAZ'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-27',
        routeId: 'baslangic-limani',
        index: 27,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'VPSKZİDN',
          'ÜADANPUN',
          'KRYYĞYUJ',
          'UMRAOROH',
          'LAABUMVR',
          'AKMBUÇAÜ',
          'KVAZUANG',
          'ÖBDIPSCR',
        ],
        targetWords: <String>['BURUN', 'KULAK', 'PARMAK', 'OMUZ', 'DİZ', 'AYAK', 'DAMAR', 'BOYUN'],
        bonusWords: <String>['SAÇ'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-28',
        routeId: 'baslangic-limani',
        index: 28,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'ZNKZEBRA',
          'TEAIDĞPH',
          'RTÜLLFVO',
          'UTİMSAHR',
          'KÖŞBJABO',
          'KELEBEKZ',
          'TAVŞANÇN',
          'SGNKEPÖK',
        ],
        targetWords: <String>['KÖPEK', 'ZEBRA', 'BALIK', 'HOROZ', 'KELEBEK', 'KURT', 'ASLAN', 'TAVŞAN'],
        bonusWords: <String>['TİMSAH'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-29',
        routeId: 'baslangic-limani',
        index: 29,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'HAREMAKİ',
          'KNCRKPNÜ',
          'LÇOROTİT',
          'AENFEBAL',
          'VIKREBOF',
          'YÇNRLLAT',
          'EEKEAREĞ',
          'TFTNENDT',
        ],
        targetWords: <String>['ROBOT', 'EKRAN', 'KLAVYE', 'TELEFON', 'KAMERA', 'TABLET', 'FARE', 'İNTERNET'],
        bonusWords: <String>['PİL'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-30',
        routeId: 'baslangic-limani',
        index: 30,
        type: WordHuntLevelType.challenge,
        grid: <String>[
          'EDVSOKAK',
          'KDENAZCE',
          'RİDÖLETO',
          'AOFAÜÇTİ',
          'PSIICKUÖ',
          'NAMTRAPA',
          'BİNAVIEĞ',
          'TRAFİKNH',
        ],
        targetWords: <String>['TRAFİK', 'SOKAK', 'BİNA', 'PARK', 'FIRIN', 'CADDE', 'APARTMAN', 'OTEL'],
        bonusWords: <String>['ECZANE'],
        timeLimitSeconds: 120,
        starRules: WordHuntStarRules(
          twoStarMaxSeconds: 100,
          threeStarMaxSeconds: 75,
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-31',
        routeId: 'baslangic-limani',
        index: 31,
        type: WordHuntLevelType.normal,
        grid: <String>['PSÜRAHİK', 'İİYKABVE', 'İMNVACPP', 'ESAUEÇJÇ', 'DTPZHMIE', 'NŞVEAADB', 'EEGŞTĞÖL', 'RĞACPRNC'],
        targetWords: <String>['TAVA', 'BIÇAK', 'RENDE', 'TEPSİ', 'SÜRAHİ', 'CEZVE', 'KEPÇE', 'MAŞA'],
        bonusWords: <String>['HUNİ'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-32',
        routeId: 'baslangic-limani',
        index: 32,
        type: WordHuntLevelType.normal,
        grid: <String>['JOTIERGĞ', 'KÖOKLYÖK', 'RTBTDBME', 'AFEAİVLM', 'VKIKVVEE', 'AURKEDKR', 'TIEINCŞJ', 'KETEHCAN'],
        targetWords: <String>['ETEK', 'CEKET', 'GÖMLEK', 'KEMER', 'BOT', 'ATKI', 'ELDİVEN', 'HIRKA'],
        bonusWords: <String>['KRAVAT'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-33',
        routeId: 'baslangic-limani',
        index: 33,
        type: WordHuntLevelType.normal,
        grid: <String>['İÇTFİÇIT', 'ICRMKNÇE', 'GRERİEŞR', 'POPEAKAZ', 'İTOBCMAİ', 'LKLRÜMİH', 'OOİEİŞGM', 'TDSBHTAK'],
        targetWords: <String>['DOKTOR', 'MİMAR', 'AŞÇI', 'TERZİ', 'POLİS', 'HAKİM', 'ÇİFTÇİ', 'BERBER'],
        bonusWords: <String>['PİLOT'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-34',
        routeId: 'baslangic-limani',
        index: 34,
        type: WordHuntLevelType.normal,
        grid: <String>['ORTAYİTS', 'NTZEPEHT', 'AİOTZAAA', 'KMAPSÜKD', 'KZETANMY', 'ÜCANARYU', 'DNİBİAKM', 'EENATSOP'],
        targetWords: <String>['MÜZE', 'SİNEMA', 'TİYATRO', 'BANKA', 'POSTANE', 'HASTANE', 'STADYUM', 'DÜKKAN'],
        bonusWords: <String>['OTOPARK'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-35',
        routeId: 'baslangic-limani',
        index: 35,
        type: WordHuntLevelType.normal,
        grid: <String>['KADNAMKK', 'EİULCHAU', 'ŞNTÇİŞZV', 'EEVNKMNA', 'AKDÖIUİT', 'ÇİKHYÇPÜ', 'PÜUOEZGL', 'ZIKKYTCÜ'],
        targetWords: <String>['MANDA', 'İNEK', 'KOYUN', 'KEÇİ', 'TAVUK', 'HİNDİ', 'ÖKÜZ', 'EŞEK'],
        bonusWords: <String>['KAZ'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-36',
        routeId: 'baslangic-limani',
        index: 36,
        type: WordHuntLevelType.normal,
        grid: <String>['NBNAĞOSP', 'ADİAGVAI', 'COGBĞÜRR', 'IMKÇEŞIA', 'LAACURMS', 'TTBRSVSA', 'AEAKUĞAL', 'PSKJÇLKH'],
        targetWords: <String>['DOMATES', 'BİBER', 'PIRASA', 'PATLICAN', 'SOĞAN', 'SARIMSAK', 'HAVUÇ', 'MARUL'],
        bonusWords: <String>['KABAK'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-37',
        routeId: 'baslangic-limani',
        index: 37,
        type: WordHuntLevelType.normal,
        grid: <String>['ÇİKEÇÇAL', 'EBNÜİNEP', 'SCDVAREA', 'NBİHEARK', 'ETTTSDTT', 'PASÇKİEA', 'RENCRVMM', 'TNUMOSKE'],
        targetWords: <String>['ÇEKİÇ', 'PENSE', 'TESTERE', 'MATKAP', 'VİDA', 'ÇİVİ', 'ANAHTAR', 'SOMUN'],
        bonusWords: <String>['METRE'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-38',
        routeId: 'baslangic-limani',
        index: 38,
        type: WordHuntLevelType.normal,
        grid: <String>['PÇNİVESÇ', 'ĞUYMERAK', 'İGSFEKFÖ', 'UHUALGÖİ', 'TKÜRBĞRN', 'UVRZUICE', 'MELOÜRRŞ', 'UKBHKNVE'],
        targetWords: <String>['SEVİNÇ', 'ÖFKE', 'KORKU', 'MERAK', 'SABIR', 'UMUT', 'NEŞE', 'HÜZÜN'],
        bonusWords: <String>['GURUR'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-39',
        routeId: 'baslangic-limani',
        index: 39,
        type: WordHuntLevelType.normal,
        grid: <String>['ÜİAVTLPF', 'CETHTORO', 'PTSÜTEMT', 'UEOOBDEO', 'TZPAEİSĞ', 'KAHRZVAR', 'EGGEPCJA', 'MİOYDARF'],
        targetWords: <String>['RADYO', 'GAZETE', 'DERGİ', 'HABER', 'MEKTUP', 'POSTA', 'FOTOĞRAF', 'VİDEO'],
        bonusWords: <String>['MESAJ'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-40',
        routeId: 'baslangic-limani',
        index: 40,
        type: WordHuntLevelType.challenge,
        grid: <String>['KMNİSANV', 'HIAŞUBAT', 'SALYRZJT', 'EOZAIYEE', 'YUCİRSKM', 'LUĞARAİM', 'ÜLIYKAMU', 'LUFZÖÖNZ'],
        targetWords: <String>['OCAK', 'ŞUBAT', 'NİSAN', 'MAYIS', 'HAZİRAN', 'TEMMUZ', 'EYLÜL', 'EKİM', 'ARALIK'],
        bonusWords: <String>['YIL'],
        timeLimitSeconds: 120,
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
          twoStarMaxSeconds: 100,
          threeStarMaxSeconds: 75,
        ),
      ),
    ],
  );
}
