import 'word_hunt_models.dart';

class WordHuntStarterContent {
  WordHuntStarterContent._();

  static const List<WordHuntInfoCard> infoCards = <WordHuntInfoCard>[
    WordHuntInfoCard(
      id: 'info-deniz',
      word: 'DENİZ',
      title: 'Deniz',
      shortFact: 'Deniz suyu, çözünmüş tuzlar nedeniyle genellikle tuzludur.',
      category: 'Doğa',
    ),
    WordHuntInfoCard(
      id: 'info-kitap',
      word: 'KİTAP',
      title: 'Kitap',
      shortFact:
          'Kitaplar bilgi, öykü ve fikirleri kalıcı olarak aktarmanın yollarından biridir.',
      category: 'Kültür',
    ),
    WordHuntInfoCard(
      id: 'info-ankara',
      word: 'ANKARA',
      title: 'Ankara',
      shortFact: 'Ankara, Türkiye’nin başkentidir.',
      category: 'Türkiye',
    ),
    WordHuntInfoCard(
      id: 'info-ari',
      word: 'ARI',
      title: 'Arı',
      shortFact: 'Arılar, birçok çiçekli bitkinin tozlaşmasına yardımcı olur.',
      category: 'Doğa',
    ),
    WordHuntInfoCard(
      id: 'info-mars',
      word: 'MARS',
      title: 'Mars',
      shortFact: 'Mars, Güneş’e uzaklık bakımından dördüncü gezegendir.',
      category: 'Uzay',
    ),
    WordHuntInfoCard(
      id: 'info-pusula',
      word: 'PUSULA',
      title: 'Pusula',
      shortFact: 'Pusula, yön bulmaya yardımcı olan bir araçtır.',
      category: 'Keşif',
    ),
  ];

  static const WordHuntRouteDefinition
  baslangicLimani = WordHuntRouteDefinition(
    id: 'baslangic-limani',
    title: 'Başlangıç Limanı',
    theme: 'liman',
    unlockStarsRequired: 18,
    routeRewardId: 'badge-kelime-yolcusu',
    plannedLevelCount: 100,
    segments: <WordHuntSegmentDefinition>[
      WordHuntSegmentDefinition(
        id: 'baslangic-limani-segment-01',
        index: 1,
        displayName: 'Segment 1',
        startLevelIndex: 1,
        endLevelIndex: 10,
      ),
      WordHuntSegmentDefinition(
        id: 'baslangic-limani-segment-02',
        index: 2,
        displayName: 'Segment 2',
        startLevelIndex: 11,
        endLevelIndex: 20,
      ),
      WordHuntSegmentDefinition(
        id: 'baslangic-limani-segment-03',
        index: 3,
        displayName: 'Segment 3',
        startLevelIndex: 21,
        endLevelIndex: 30,
      ),
    ],
    levels: <WordHuntLevelDefinition>[
      WordHuntLevelDefinition(
        id: 'baslangic-1',
        routeId: 'baslangic-limani',
        index: 1,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'BHVFKNÇL',
          'MROTAMBK',
          'GZGBLITÜ',
          'EJÖİEOGS',
          'MEELMASA',
          'ZFOGÖORF',
          'ESTİOYUN',
          'LYUARFCÜ',
        ],
        targetWords: <String>['KALEM', 'MASA', 'OYUN', 'ROTA', 'BİLGİ'],
        bonusWords: <String>['ELMA'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-2',
        routeId: 'baslangic-limani',
        index: 2,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'CĞAPİÇCL',
          'MIUGEMİP',
          'PMARTILG',
          'HLÜDBÜHR',
          'EİĞEAÖIF',
          'VMJNTLÜŞ',
          'SAHİLUGÇ',
          'ANJZSLTA',
        ],
        targetWords: <String>['DENİZ', 'GEMİ', 'LİMAN', 'DALGA', 'SAHİL'],
        bonusWords: <String>['MARTI'],
        infoCardIds: <String>['info-deniz'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-3',
        routeId: 'baslangic-limani',
        index: 3,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'ŞĞEÖÜNAG',
          'RMDSAUKĞ',
          'DERSISAS',
          'VLKHONĞA',
          'PATİKSIY',
          'OKULNRTF',
          'TÜSKÜMFA',
          'ŞNPHHLĞG',
        ],
        targetWords: <String>[
          'KİTAP',
          'OKUL',
          'SINIF',
          'KAĞIT',
          'DERS',
          'ÖDEV',
        ],
        bonusWords: <String>['SAYFA'],
        infoCardIds: <String>['info-kitap'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-4',
        routeId: 'baslangic-limani',
        index: 4,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'GIVJIÇOK',
          'FBLKKĞDF',
          'SMCZUUEŞ',
          'AAZJIDRP',
          'ABIAEHÜÖ',
          'TSDHMCSD',
          'FDKUBAÇF',
          'YIKOŞUNĞ',
        ],
        targetWords: <String>[
          'HIZLI',
          'ZAMAN',
          'SÜRE',
          'HEDEF',
          'ÇABUK',
          'SAAT',
        ],
        bonusWords: <String>['KOŞU'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-5',
        routeId: 'baslangic-limani',
        index: 5,
        type: WordHuntLevelType.challenge,
        grid: <String>[
          'ANKARAJB',
          'TÜRKİYEA',
          'OMOVÜAKŞ',
          'ÖÇEGÜNUK',
          'OZZCZILE',
          'KALELTEN',
          'OVFĞZİÜT',
          'ŞEHİRZSÜ',
        ],
        targetWords: <String>[
          'ANKARA',
          'ŞEHİR',
          'TÜRKİYE',
          'BAŞKENT',
          'MECLİS',
          'KULE',
          'KALE',
        ],
        bonusWords: <String>['ANIT'],
        infoCardIds: <String>['info-ankara'],
        timeLimitSeconds: 60,
        starRules: WordHuntStarRules(
          twoStarMaxSeconds: 50,
          threeStarMaxSeconds: 35,
          twoStarMaxMistakes: 1,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-6',
        routeId: 'baslangic-limani',
        index: 6,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'ŞIIYYNÜG',
          'ÇİÇEKNIK',
          'ÇNŞPAĞAÇ',
          'RİIMRRRİ',
          'LDRYPİPO',
          'ROROAHÇE',
          'YĞTÖYEAN',
          'FAZRÜNKY',
        ],
        targetWords: <String>[
          'DOĞA',
          'ORMAN',
          'AĞAÇ',
          'ÇİÇEK',
          'TOPRAK',
          'YEŞİL',
          'NEHİR',
        ],
        bonusWords: <String>['YAPRAK'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-7',
        routeId: 'baslangic-limani',
        index: 7,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'IŞKZNTEM',
          'MRBKRİEO',
          'GHAEAYOD',
          'RĞLTVNNO',
          'IİÇEKAAY',
          'YKNPVEŞT',
          'ADPOLENÖ',
          'ÇUKÖSÇNP',
        ],
        targetWords: <String>[
          'ARI',
          'MEYVE',
          'BAL',
          'KOVAN',
          'KANAT',
          'POLEN',
          'PETEK',
          'NEKTAR',
        ],
        bonusWords: <String>['ÇAYIR'],
        infoCardIds: <String>['info-ari'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-8',
        routeId: 'baslangic-limani',
        index: 8,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'ILFAULİU',
          'ĞMAÇSDCŞ',
          'ÇHIZSNLO',
          'AGMKUVÇK',
          'İPRYAKVG',
          'VROKSTLO',
          'İÇPTHVÖL',
          'PÇSPÖVÜP',
        ],
        targetWords: <String>[
          'SPOR',
          'TOP',
          'FAUL',
          'OYUNCU',
          'TAKIM',
          'GOL',
          'MAÇ',
        ],
        bonusWords: <String>['HIZ', 'SKOR'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-9',
        routeId: 'baslangic-limani',
        index: 9,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'VGRETARK',
          'NEGEZEGZ',
          'NİKESGÜI',
          'ĞOGUÜNDD',
          'RGYNMÜYL',
          'ÜDETNRAI',
          'UŞZYFÖZY',
          'ÜMARSYUÜ',
        ],
        targetWords: <String>[
          'MARS',
          'UZAY',
          'YILDIZ',
          'GEZEGEN',
          'GÜNEŞ',
          'DÜNYA',
          'UYDU',
          'KRATER',
          'YÖRÜNGE',
        ],
        bonusWords: <String>['ROKET'],
        infoCardIds: <String>['info-mars'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-10',
        routeId: 'baslangic-limani',
        index: 10,
        type: WordHuntLevelType.routeFinal,
        grid: <String>[
          'MHEDEFYP',
          'NATPAKAA',
          'FZCYOLTR',
          'FİLEUİIK',
          'İNRSRDUU',
          'ŞEUALADR',
          'EPHUCUPİ',
          'KNİŞANIB',
        ],
        targetWords: <String>[
          'PUSULA',
          'YOL',
          'İPUCU',
          'PARKUR',
          'NİŞAN',
          'KEŞİF',
          'HARİTA',
          'MACERA',
          'KAPTAN',
        ],
        bonusWords: <String>['HAZİNE'],
        infoCardIds: <String>['info-pusula'],
        timeLimitSeconds: 120,
        starRules: WordHuntStarRules(
          twoStarMaxSeconds: 100,
          threeStarMaxSeconds: 75,
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-11',
        routeId: 'baslangic-limani',
        index: 11,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'ĞNLÖLİAĞ',
          'IHPKÖNÖT',
          'FİDÖRENK',
          'NOZTVTÖA',
          'AİÜHUPUD',
          'DODZRLDR',
          'İZSÜTÜUA',
          'FNZIÇBNB',
        ],
        targetWords: <String>['BARDAK', 'KÖPRÜ', 'BULUT', 'RENK'],
        bonusWords: <String>['FİDAN'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 3,
          threeStarMaxMistakes: 1,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-12',
        routeId: 'baslangic-limani',
        index: 12,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'BFUIZSDÖ',
          'KCLPIMUM',
          'SRIÖUJRŞ',
          'ZERAKEMY',
          'AMHİTTUU',
          'HĞZFŞNKÇ',
          'TÜEZLAAL',
          'MDYHÖLRÇ',
        ],
        targetWords: <String>['ÇANTA', 'MÜZİK', 'KUMRU', 'DEFTER'],
        bonusWords: <String>['DÜĞME'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 3,
          threeStarMaxMistakes: 1,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-13',
        routeId: 'baslangic-limani',
        index: 13,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'OJFRBYĞE',
          'NODMĞYCŞ',
          'EZĞIEEPÖ',
          'GAEDREPF',
          'DRLÇJÇÖÜ',
          'HİDEKHZH',
          'BKITSAYN',
          'İAİNUBAS',
        ],
        targetWords: <String>['BAHÇE', 'KEDİ', 'PERDE', 'SABUN', 'YASTIK'],
        bonusWords: <String>['KİRAZ'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 3,
          threeStarMaxMistakes: 1,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-14',
        routeId: 'baslangic-limani',
        index: 14,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'ÖVHUBMAB',
          'ÖTARAKİE',
          'ŞTĞGMFRB',
          'ÖÇBÖOETÇ',
          'FORİCNİP',
          'İRFNUESU',
          'EAETCYGS',
          'HPIÇTCŞF',
        ],
        targetWords: <String>['VAGON', 'BAMBU', 'İNCİR', 'TARAK', 'PENCERE'],
        bonusWords: <String>['ÇORAP'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-15',
        routeId: 'baslangic-limani',
        index: 15,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'RRTŞSUMD',
          'ZPÇUVMBÜ',
          'LNCERNNR',
          'AFĞCJNNB',
          'SĞYÖIUAÜ',
          'MERDİVEN',
          'UCRÇUADO',
          'KŞZLLKKT',
        ],
        targetWords: <String>['KUMSAL', 'TURNA', 'BAVUL', 'KAVUN', 'MERDİVEN'],
        bonusWords: <String>['DÜRBÜN'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-16',
        routeId: 'baslangic-limani',
        index: 16,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'ĞBIKGACĞ',
          'SKFNMUAM',
          'KEMANJMF',
          'ÇŞKCPHHI',
          'HARRĞESR',
          'SPBECDDÇ',
          'SKUMANDA',
          'JALSÇVÜR',
        ],
        targetWords: <String>['MERCAN', 'ŞAPKA', 'MAKAS', 'KEMAN', 'KUMANDA'],
        bonusWords: <String>['FIRÇA'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-17',
        routeId: 'baslangic-limani',
        index: 17,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'FHMĞUÜOZ',
          'UYILZFGE',
          'PYTITÖCY',
          'İYELKENT',
          'YİTUMRAİ',
          'AŞNKZILN',
          'NPEŞİŞGN',
          'OÇBRIÇAC',
        ],
        targetWords: <String>['ZEYTİN', 'ARMUT', 'ÇEKMECE', 'PİYANO', 'ŞİŞE'],
        bonusWords: <String>['YELKEN'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-18',
        routeId: 'baslangic-limani',
        index: 18,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'IÜZUPRAK',
          'CMĞGAÜEH',
          'VKKPŞLRZ',
          'BİSİKLET',
          'PELAHBCG',
          'TTZRVZNK',
          'DAIZİVEC',
          'KEDRÖOTR',
        ],
        targetWords: <String>[
          'KARPUZ',
          'TENCERE',
          'ÖRDEK',
          'BİSİKLET',
          'CEVİZ',
        ],
        bonusWords: <String>['KAZAK'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-19',
        routeId: 'baslangic-limani',
        index: 19,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'İHZGPEÖD',
          'ŞTAİNÇAI',
          'KLHPVRYS',
          'GABRÜMÖK',
          'ŞAYIEOŞA',
          'EYLADNAS',
          'GAJKKŞER',
          'HÇĞKPTJF',
        ],
        targetWords: <String>['FENER', 'SAKSI', 'KAYAK', 'HALI', 'SANDALYE'],
        bonusWords: <String>['KÖMÜR'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-20',
        routeId: 'baslangic-limani',
        index: 20,
        type: WordHuntLevelType.challenge,
        grid: <String>[
          'BÖÜHONIJ',
          'MANDALTŞ',
          'RŞEMSİYE',
          'CAMĞCRGZ',
          'YKASABAM',
          'NOLOTNAP',
          'KEDRİKEÇ',
          'LAKATROP',
        ],
        targetWords: <String>[
          'PANTOLON',
          'PORTAKAL',
          'ŞEMSİYE',
          'KASABA',
          'ÇEKİRDEK',
        ],
        bonusWords: <String>['MANDAL'],
        timeLimitSeconds: 120,
        starRules: WordHuntStarRules(
          twoStarMaxSeconds: 100,
          threeStarMaxSeconds: 75,
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-21',
        routeId: 'baslangic-limani',
        index: 21,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'ŞŞĞÇAKİU',
          'RVCSAKTY',
          'TNKEBPSY',
          'HZAUZHEO',
          'YIBFNİÇR',
          'ILATAÇVG',
          'KYTÇKUPA',
          'TYUKRÇKN',
        ],
        targetWords: <String>['AVİZE', 'TABAK', 'ÇATAL', 'YORGAN'],
        bonusWords: <String>['KUPA'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 3,
          threeStarMaxMistakes: 1,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-22',
        routeId: 'baslangic-limani',
        index: 22,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'EVĞILÜUŞ',
          'OSLTĞLEN',
          'VÜOJVKDY',
          'İNPALODC',
          'SGHŞYLRK',
          'TERNPTÜS',
          'URAISUUY',
          'KBTEYKÜR',
        ],
        targetWords: <String>['KOLTUK', 'DOLAP', 'HAVLU', 'BANYO'],
        bonusWords: <String>['SÜNGER'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 3,
          threeStarMaxMistakes: 1,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-23',
        routeId: 'baslangic-limani',
        index: 23,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'OŞOFÖRZE',
          'LLABSÇLL',
          'KARUDÜPO',
          'ÇNÇMFUTV',
          'OİLJJOAJ',
          'TELİBPKD',
          'HEHÜUYSV',
          'AJSRZKİÇ',
        ],
        targetWords: <String>['OTOBÜS', 'TAKSİ', 'DURAK', 'BİLET', 'ŞOFÖR'],
        bonusWords: <String>['VAPUR'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-24',
        routeId: 'baslangic-limani',
        index: 24,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'CJCÖTDKR',
          'TZNHFĞAE',
          'RZTDŞİŞÇ',
          'UİCKFEIE',
          'ĞANVKKKL',
          'OICYJMGE',
          'YZHKERÖÇ',
          'ODIKÖPÖM',
        ],
        targetWords: <String>['EKMEK', 'PEYNİR', 'YOĞURT', 'REÇEL', 'ÇÖREK'],
        bonusWords: <String>['KAŞIK'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-25',
        routeId: 'baslangic-limani',
        index: 25,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'KKÜÜPYŞV',
          'BUNVOÖFM',
          'VSÇOEÜKT',
          'IIŞSEPET',
          'VİPÜOKIZ',
          'FHÖAİAİK',
          'HUYTRSSH',
          'FTEKRAMP',
        ],
        targetWords: <String>['MARKET', 'SEPET', 'KASA', 'PARA', 'FİŞ'],
        bonusWords: <String>['ETİKET'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-26',
        routeId: 'baslangic-limani',
        index: 26,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'CABKZSEH',
          'SAĞANAKİ',
          'SMYŞFÜIT',
          'ŞAKUZĞRN',
          'FSLKŞJAE',
          'GOPKMKĞS',
          'DPKÖGKIİ',
          'AÜÇGUCAÇ',
        ],
        targetWords: <String>[
          'GÖKKUŞAK',
          'DOLU',
          'KIRAĞI',
          'ÇİSENTİ',
          'SAĞANAK',
        ],
        bonusWords: <String>['AYAZ'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-27',
        routeId: 'baslangic-limani',
        index: 27,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'SPFGYSKD',
          'ZRAÇZÇKH',
          'SBURUNAL',
          'ŞEBZMFLS',
          'FMLFOAUH',
          'ŞŞŞOADKC',
          'ÖBĞJGUİK',
          'LAMULHEZ',
        ],
        targetWords: <String>['BURUN', 'KULAK', 'PARMAK', 'OMUZ', 'DİZ'],
        bonusWords: <String>['SAÇ'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-28',
        routeId: 'baslangic-limani',
        index: 28,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'ĞÖHJŞKSF',
          'ZOROHEÇÜ',
          'UCEBALIK',
          'İKHRSECÖ',
          'SKBAMBJP',
          'YEUMİEHE',
          'ZFÖNTKJK',
          'KZAKÇİCG',
        ],
        targetWords: <String>['KÖPEK', 'ZEBRA', 'BALIK', 'HOROZ', 'KELEBEK'],
        bonusWords: <String>['TİMSAH'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-29',
        routeId: 'baslangic-limani',
        index: 29,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'VKHNZKIK',
          'NROAÜLÇE',
          'FOSRKAÇÜ',
          'ÜBFKRVŞJ',
          'ÇOIEÜYEE',
          'UTMMLEKR',
          'TAĞİEEZT',
          'KJPÖPRTY',
        ],
        targetWords: <String>['ROBOT', 'EKRAN', 'KLAVYE', 'TELEFON', 'KAMERA'],
        bonusWords: <String>['PİL'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'baslangic-30',
        routeId: 'baslangic-limani',
        index: 30,
        type: WordHuntLevelType.challenge,
        grid: <String>[
          'UBĞPYZİK',
          'UİKFCPGO',
          'ECVPIATI',
          'NSÜDBRNC',
          'AODİAKIZ',
          'ZKNFTKIN',
          'CAİVKRUV',
          'EKOLHKFO',
        ],
        targetWords: <String>['TRAFİK', 'SOKAK', 'BİNA', 'PARK', 'FIRIN'],
        bonusWords: <String>['ECZANE'],
        timeLimitSeconds: 120,
        starRules: WordHuntStarRules(
          twoStarMaxSeconds: 100,
          threeStarMaxSeconds: 75,
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
    ],
  );
}
