import 'word_hunt_models.dart';

class WordHuntGokyuzuContent {
  WordHuntGokyuzuContent._();

  static const List<WordHuntInfoCard> infoCards = <WordHuntInfoCard>[
    WordHuntInfoCard(
      id: 'gok-info-ruzgar',
      word: 'RÜZGAR',
      title: 'Rüzgâr',
      shortFact:
          'Rüzgâr, havanın basınç farkları nedeniyle hareket etmesiyle oluşur.',
      category: 'Doğa',
    ),
    WordHuntInfoCard(
      id: 'gok-info-bulut',
      word: 'BULUT',
      title: 'Bulut',
      shortFact:
          'Bulutlar, havadaki çok küçük su damlacıkları veya buz kristallerinden oluşur.',
      category: 'Doğa',
    ),
    WordHuntInfoCard(
      id: 'gok-info-kartal',
      word: 'KARTAL',
      title: 'Kartal',
      shortFact:
          'Kartallar, güçlü görme yetileriyle bilinen yırtıcı kuşlardır.',
      category: 'Doğa',
    ),
    WordHuntInfoCard(
      id: 'gok-info-yildirim',
      word: 'YILDIRIM',
      title: 'Yıldırım',
      shortFact:
          'Yıldırım, atmosferde gerçekleşen güçlü bir elektrik boşalmasıdır.',
      category: 'Doğa',
    ),
    WordHuntInfoCard(
      id: 'gok-info-teleskop',
      word: 'TELESKOP',
      title: 'Teleskop',
      shortFact:
          'Teleskoplar, uzaktaki gök cisimlerinden gelen ışığı toplamaya yardımcı olur.',
      category: 'Uzay',
    ),
    WordHuntInfoCard(
      id: 'gok-info-gunes',
      word: 'GÜNEŞ',
      title: 'Güneş',
      shortFact: 'Güneş, Dünya’ya en yakın yıldızdır.',
      category: 'Uzay',
    ),
  ];

  static const WordHuntRouteDefinition gokyuzuAdalari = WordHuntRouteDefinition(
    id: 'gokyuzu-adalari',
    title: 'Gökyüzü Adaları',
    theme: 'gokyuzu',
    unlockStarsRequired: 18,
    routeRewardId: 'badge-gokyuzu-kasifi',
    levels: <WordHuntLevelDefinition>[
      WordHuntLevelDefinition(
        id: 'gokyuzu-1',
        routeId: 'gokyuzu-adalari',
        index: 1,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'DPSBDUNK',
          'VBEMYOFL',
          'EURAGZÜR',
          'SÇALYKĞH',
          'BUPUTAVF',
          'ÖŞESİNTİ',
          'UJUUVABV',
          'ZTFPOTTO',
        ],
        targetWords: <String>['RÜZGAR', 'ESİNTİ', 'SERAP', 'KANAT', 'UÇUŞ'],
        bonusWords: <String>['PUSULA'],
        infoCardIds: <String>['gok-info-ruzgar'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'gokyuzu-2',
        routeId: 'gokyuzu-adalari',
        index: 2,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'HLNTMGZĞ',
          'ÜYİUZZJÇ',
          'UŞALŞMCİ',
          'ÖKAUUİAÇ',
          'LİLBAHÇE',
          'TOMURCUK',
          'PEAZHPDI',
          'OŞDGÖLGE',
        ],
        targetWords: <String>['BULUT', 'ÇİÇEK', 'BAHÇE', 'DAMLA', 'GÖLGE'],
        bonusWords: <String>['TOMURCUK'],
        infoCardIds: <String>['gok-info-bulut'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'gokyuzu-3',
        routeId: 'gokyuzu-adalari',
        index: 3,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'BÖKAÇUTŞ',
          'PMSŞGÜDU',
          'ELĞJYKÇG',
          'NASLSUÇA',
          'ÇTEOŞIVG',
          'ERRÖÖMZA',
          'LAÇHZDAJ',
          'SKENCMÜH',
        ],
        targetWords: <String>[
          'PENÇE',
          'TÜYLER',
          'YUVA',
          'UÇAK',
          'GAGA',
          'KARTAL',
        ],
        bonusWords: <String>['SERÇE'],
        infoCardIds: <String>['gok-info-kartal'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'gokyuzu-4',
        routeId: 'gokyuzu-adalari',
        index: 4,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'ZGÇMRENK',
          'ÜAMZİRPB',
          'KIŞIUKZD',
          'UMVMÖIVV',
          'YIĞPRZÜZ',
          'PARLAKBJ',
          'YÜKYVÇEI',
          'BBZÜDNÜG',
        ],
        targetWords: <String>[
          'RENK',
          'KÖPRÜ',
          'YAĞMUR',
          'GÜNDÜZ',
          'IŞIK',
          'PRİZMA',
        ],
        bonusWords: <String>['PARLAK'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'gokyuzu-5',
        routeId: 'gokyuzu-adalari',
        index: 5,
        type: WordHuntLevelType.challenge,
        grid: <String>[
          'ÜRMELTEM',
          'TULUBDIÇ',
          'LANITRIF',
          'ÜENÜIZII',
          'REEDUMAN',
          'ÜELUKPÜZ',
          'GIKEŞMİŞ',
          'YAĞIŞRPH',
        ],
        targetWords: <String>[
          'FIRTINA',
          'ŞİMŞEK',
          'KULE',
          'MELTEM',
          'YAĞIŞ',
          'DUMAN',
          'GÜRÜLTÜ',
        ],
        bonusWords: <String>['YILDIRIM'],
        infoCardIds: <String>['gok-info-yildirim'],
        timeLimitSeconds: 60,
        starRules: WordHuntStarRules(
          twoStarMaxSeconds: 50,
          threeStarMaxSeconds: 35,
          twoStarMaxMistakes: 1,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'gokyuzu-6',
        routeId: 'gokyuzu-adalari',
        index: 6,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'RĞÜBALON',
          'EGEMİİFP',
          'LNNMRSĞC',
          'PDAOHKBT',
          'ENTVŞEAE',
          'NOPÖRLTÖ',
          'MBAŞAESÖ',
          'HLKHIHPB',
        ],
        targetWords: <String>[
          'GEMİ',
          'BALON',
          'LİMAN',
          'PERVANE',
          'MOTOR',
          'HALAT',
          'İSKELE',
        ],
        bonusWords: <String>['KAPTAN'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'gokyuzu-7',
        routeId: 'gokyuzu-adalari',
        index: 7,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'MKHRIPUE',
          'LIİIGARL',
          'AŞLHÖTZS',
          'MIATKHIİ',
          'BHLIYEDL',
          'AYMMÜMLÜ',
          'ECEGZJIE',
          'VELAÜYYT',
        ],
        targetWords: <String>[
          'GECE',
          'YILDIZ',
          'ALEV',
          'RIHTIM',
          'LAMBA',
          'SİLÜET',
          'GÖKYÜZÜ',
          'HİLAL',
        ],
        bonusWords: <String>['MEHTAP'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'gokyuzu-8',
        routeId: 'gokyuzu-adalari',
        index: 8,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'YAJJEAAİ',
          'GTNSRDEL',
          'İİAAÜDNZ',
          'ZRĞNHÇİİ',
          'EALDŞTZG',
          'MHSIRLAR',
          'LÜTKECHR',
          'LRZRIEZC',
        ],
        targetWords: <String>[
          'GİZEM',
          'MAĞARA',
          'ANAHTAR',
          'SANDIK',
          'HARİTA',
          'İZLER',
          'GİZLİ',
        ],
        bonusWords: <String>['SIRLAR', 'HAZİNE'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'gokyuzu-9',
        routeId: 'gokyuzu-adalari',
        index: 9,
        type: WordHuntLevelType.normal,
        grid: <String>[
          'PINERVEN',
          'KOŞOYYCE',
          'İSKALAGG',
          'BEZSTNÜE',
          'TUSKEKAZ',
          'MNIŞILÖE',
          'YÖRÜNGEG',
          'ROETEMZT',
        ],
        targetWords: <String>[
          'METEOR',
          'UZAY',
          'TELESKOP',
          'GEZEGEN',
          'GÖKTAŞI',
          'EVREN',
          'YÖRÜNGE',
          'IŞIN',
          'GALAKSİ',
        ],
        bonusWords: <String>['ROKET'],
        infoCardIds: <String>['gok-info-teleskop'],
        starRules: WordHuntStarRules(
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
      WordHuntLevelDefinition(
        id: 'gokyuzu-10',
        routeId: 'gokyuzu-adalari',
        index: 10,
        type: WordHuntLevelType.routeFinal,
        grid: <String>[
          'ARECAMEG',
          'LRIŞIKÖÜ',
          'TBEAAKRN',
          'IHSFYPEE',
          'NOAÜAVLŞ',
          'GŞZTRZKU',
          'AÜÜİAOÖL',
          'SÇZISCGE',
        ],
        targetWords: <String>[
          'GÜNEŞ',
          'SARAY',
          'ALTIN',
          'TAHT',
          'ŞULE',
          'ZİRVE',
          'ŞAFAK',
          'GÖKLER',
          'MACERA',
        ],
        bonusWords: <String>['ZAFER'],
        infoCardIds: <String>['gok-info-gunes'],
        timeLimitSeconds: 120,
        starRules: WordHuntStarRules(
          twoStarMaxSeconds: 100,
          threeStarMaxSeconds: 75,
          twoStarMaxMistakes: 2,
          threeStarMaxMistakes: 0,
        ),
      ),
    ],
  );
}
